"""Traceability overlay — manual annotations layered on auto-generated matrix.

The auto-generated matrix is regenerated by `scripts/build_traceability.py`
and would otherwise wipe out any manual rows (FR-06 §3.x mapping, FR-ENF-01..03,
the FR-without-SRS annotations, the "Manual annotations" warning).

The overlay file (`TRACEABILITY_MATRIX.overlay.yaml`) carries:
  - `overrides`: per-FR overrides for status / code_files / test_files /
    sad_module. These win over the auto-generated values for the same FR.
  - `annotations`: per-FR free-text notes appended to the row. Never affect
    gates, never block.

`merge_overlay(atomic, overlay)` returns a new dict; the atomic dict is not
mutated. `render_markdown(merged)` produces a markdown string with
`<!-- AUTO-GEN:START/END -->` sentinels around the auto-generated table.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml


# Sentinels bracket the auto-generated section so the migration tool can
# safely rewrite that block without touching manual content above/below.
AUTO_GEN_START = "<!-- AUTO-GEN:START -->"
AUTO_GEN_END = "<!-- AUTO-GEN:END -->"
OVERLAY_SCHEMA = "harness/traceability/overlay/v1"


# ---------------------------------------------------------------------------
# Overlay loading and validation
# ---------------------------------------------------------------------------

def load_overlay(path: Optional[Path]) -> Dict[str, Any]:
    """Load overlay YAML. Returns {} if file is missing or empty.

    Never raises on missing file — overlay is optional. Raises on malformed
    YAML (the validator runs before this returns).
    """
    if path is None or not path.exists():
        return {}
    text = path.read_text(encoding="utf-8", errors="replace")
    if not text.strip():
        return {}
    data = yaml.safe_load(text)
    if not isinstance(data, dict):
        return {}
    return data


def validate_overlay(data: Dict[str, Any]) -> List[str]:
    """Return a list of schema error strings; empty list means OK.

    Never raises. Callers should print the errors and fall back to no
    overlay (so the auto-generated matrix still renders).
    """
    errors: List[str] = []

    schema = data.get("schema")
    if schema is not None and schema != OVERLAY_SCHEMA:
        errors.append(
            f"overlay schema {schema!r} != {OVERLAY_SCHEMA!r}; "
            f"this build expects {OVERLAY_SCHEMA}"
        )

    overrides = data.get("overrides", [])
    if not isinstance(overrides, list):
        errors.append("`overrides` must be a list")
        overrides = []
    for i, ov in enumerate(overrides):
        if not isinstance(ov, dict):
            errors.append(f"overrides[{i}] must be a mapping")
            continue
        if "fr_id" not in ov:
            errors.append(f"overrides[{i}] missing required 'fr_id'")
        allowed = {"fr_id", "status", "code_files", "test_files",
                   "sad_module", "justification"}
        unknown = set(ov.keys()) - allowed
        if unknown:
            errors.append(
                f"overrides[{i}] has unknown keys: {sorted(unknown)}"
            )
        for list_key in ("code_files", "test_files"):
            if list_key in ov and not isinstance(ov[list_key], list):
                errors.append(f"overrides[{i}].{list_key} must be a list")

    annotations = data.get("annotations", [])
    if not isinstance(annotations, list):
        errors.append("`annotations` must be a list")
    else:
        for i, ann in enumerate(annotations):
            if not isinstance(ann, dict):
                errors.append(f"annotations[{i}] must be a mapping")
                continue
            if "fr_id" not in ann:
                errors.append(f"annotations[{i}] missing required 'fr_id'")
            if "note" not in ann:
                errors.append(f"annotations[{i}] missing required 'note'")

    return errors


# ---------------------------------------------------------------------------
# Merge
# ---------------------------------------------------------------------------

def merge_overlay(atomic: Dict[str, Any], overlay: Dict[str, Any]) -> Dict[str, Any]:
    """Return a merged matrix dict; overlay wins for any FR it touches.

    `atomic` shape: {"requirements": {fr_id: {status, code_files, test_files,
    sad_module, ...}}, "completeness": {...}, "missing": {...}}
    `overlay` shape: see OVERLAY_SCHEMA.
    """
    merged_requirements: Dict[str, Dict[str, Any]] = {}
    for fr_id, row in atomic.get("requirements", {}).items():
        merged_requirements[fr_id] = dict(row)  # shallow copy

    for ov in overlay.get("overrides", []):
        fr_id = ov.get("fr_id")
        if not fr_id:
            continue
        row = merged_requirements.setdefault(fr_id, {"fr_id": fr_id})
        for key in ("status", "code_files", "test_files", "sad_module", "justification"):
            if key in ov:
                row[key] = ov[key]

    # Annotations are stored as a sibling list; the renderer joins them into
    # the per-FR row string when --annotations are present in the row.
    annotations_by_fr: Dict[str, List[str]] = {}
    for ann in overlay.get("annotations", []):
        fr_id = ann.get("fr_id")
        note = ann.get("note")
        if fr_id and note:
            annotations_by_fr.setdefault(fr_id, []).append(str(note))

    return {
        "schema_version": OVERLAY_SCHEMA,
        "project_id": atomic.get("project_id"),
        "completeness": atomic.get("completeness", {}),
        "missing": atomic.get("missing", {}),
        "requirements": merged_requirements,
        "annotations": annotations_by_fr,
    }


# ---------------------------------------------------------------------------
# Atomic dict (built from RequirementTraceability)
# ---------------------------------------------------------------------------

def atomic_to_dict(rt) -> Dict[str, Any]:
    """Convert a RequirementTraceability model to a plain-dict atomic form.

    Import is local to avoid an import cycle: `requirement_traceability.py`
    should not depend on the overlay module.
    """
    completeness = rt.verify_completeness()
    requirements: Dict[str, Dict[str, Any]] = {}
    for rid, req in sorted(rt.requirements.items()):
        meta = req.metadata or {}
        requirements[rid] = {
            "fr_id": rid,
            "status": req.status.value,
            "srs_section": req.srs_section,
            "code_files": list(meta.get("code_files", [])),
            "test_files": list(meta.get("test_files", [])),
            "sad_module": (meta.get("sad_modules") or ["—"])[0]
                          if meta.get("sad_modules") else "—",
            "priority": req.priority,
        }
    return {
        "project_id": rt.project_id,
        "completeness": completeness,
        "missing": completeness.get("missing_mappings", {}),
        "requirements": requirements,
    }


# ---------------------------------------------------------------------------
# Render markdown with sentinels
# ---------------------------------------------------------------------------

def _fmt_files(files, limit: int = 3) -> str:
    if not files:
        return "—"
    head = ", ".join(files[:limit])
    if len(files) > limit:
        head += f" (+{len(files) - limit})"
    return head


def render_markdown(merged: Dict[str, Any]) -> str:
    """Render merged matrix as markdown. Sentinels wrap the auto-gen table.

    The intro (header + compliance summary) is also inside the sentinels —
    everything regenerated belongs to the harness. Manual content can live
    above the START sentinel and is preserved on subsequent runs.
    """
    completeness = merged.get("completeness", {})
    requirements = merged.get("requirements", {})
    missing = merged.get("missing", {})
    annotations = merged.get("annotations", {})

    frs_srs = set(requirements.keys()) - set(missing.get("fr_without_srs", []))
    frs_code = set(requirements.keys()) - set(missing.get("fr_without_code", []))
    frs_test = set(requirements.keys()) - set(missing.get("fr_without_test", []))
    total = max(len(requirements), 1)

    lines: List[str] = []
    lines.extend([
        AUTO_GEN_START,
        "# Traceability Matrix",
        "",
        "> Auto-generated by `scripts/build_traceability.py`",
        f"> Project: `{merged.get('project_id', 'unknown')}`",
        "> Edit `TRACEABILITY_MATRIX.overlay.yaml` for manual rows.",
        "",
        "## ASPICE Compliance Summary",
        "",
        "| Metric | Value | Target |",
        "|--------|-------|--------|",
        f"| Total Requirements | {completeness.get('total_requirements', 0)} | — |",
        f"| SRS Coverage | {completeness.get('srs_coverage', '0%')} | 100% |",
        f"| Code Coverage | {completeness.get('code_coverage', '0%')} | 100% |",
        f"| Test Coverage | {completeness.get('test_coverage', '0%')} | 100% |",
        f"| Verification Rate | {completeness.get('verification_rate', '0%')} | 100% |",
        f"| Total Links | {completeness.get('total_links', 0)} | — |",
        "",
        "### ASPICE SWE.3 Compliance",
        "",
        "| Practice | Status | Coverage |",
        "|----------|--------|----------|",
        f"| SWE.3 BP1: FR→SRS | {'PASS' if len(frs_srs) == total else 'FAIL'} | {len(frs_srs)}/{total} |",
        f"| SWE.3 BP2: SRS→Code | {'PASS' if len(frs_code) == total else 'FAIL'} | {len(frs_code)}/{total} |",
        f"| SWE.3 BP3: Code→Test | {'PASS' if len(frs_test) == total else 'FAIL'} | {len(frs_test)}/{total} |",
        "",
        "## Detailed Traceability Matrix",
        "",
        "| Requirement | Status | Code Files | Test Files | SAD Module |",
        "|-------------|--------|------------|------------|------------|",
    ])

    for rid, row in sorted(requirements.items()):
        code_str = _fmt_files(row.get("code_files", []))
        test_str = _fmt_files(row.get("test_files", []))
        sad_str = row.get("sad_module") or "—"
        if annotations.get(rid):
            # Join multiple annotations with "; " so the renderer matches
            # the bucketing design in merge_overlay (annotations is a list).
            sad_str += f" _(annotation: {'; '.join(annotations[rid])})_"
        justification = row.get("justification")
        if justification:
            sad_str += f"<br><sub>{justification}</sub>"
        lines.append(
            f"| {rid} | {row.get('status', 'pending')} | "
            f"{code_str} | {test_str} | {sad_str} |"
        )

    if any(missing.values()):
        lines.extend(["", "## Gaps", ""])
        for label, ids in [
            ("FR without SRS mapping", missing.get("fr_without_srs", [])),
            ("FR without Code", missing.get("fr_without_code", [])),
            ("FR without Test", missing.get("fr_without_test", [])),
        ]:
            if ids:
                lines.append(f"- **{label}**: {', '.join(sorted(ids))}")

    lines.append(AUTO_GEN_END)
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Top-level orchestration (used by the script and by the migrate CLI)
# ---------------------------------------------------------------------------

def render_atomic_markdown(rt) -> str:
    """Render the matrix with no overlay (atomic-only).

    Convenience for callers that don't have an overlay file.
    """
    return render_markdown(atomic_to_dict(rt))


def render_merged_markdown(rt, overlay_path: Optional[Path]) -> tuple[str, list[str]]:
    """Render the merged matrix (atomic + overlay). Returns (markdown, errors).

    `errors` is non-empty if the overlay failed validation; the markdown
    returned is the atomic-only fallback so the script still produces output.
    """
    atomic = atomic_to_dict(rt)
    overlay = load_overlay(overlay_path)
    errs = validate_overlay(overlay) if overlay else []
    if errs:
        return render_markdown(atomic), errs
    merged = merge_overlay(atomic, overlay)
    return render_markdown(merged), []


# ---------------------------------------------------------------------------
# Migration helper (PR 2: `migrate-trace-overlay` CLI subcommand)
# ---------------------------------------------------------------------------

def migrate_existing_matrix(
    matrix_path: Path,
    overlay_path: Path,
    dry_run: bool = False,
) -> dict:
    """Wrap a sentinel-less TRACEABILITY_MATRIX.md in AUTO-GEN sentinels.

    Returns a dict describing what would change. The function does NOT
    attempt to extract manual rows from the existing file into the overlay
    (that's a per-project human task; this tool just makes the file
    forward-compatible with subsequent regenerations).

    If the matrix already has sentinels, returns {"status": "already-migrated"}.
    If the matrix is missing, returns {"status": "missing"}.
    """
    if not matrix_path.exists():
        return {"status": "missing", "matrix": str(matrix_path)}

    existing = matrix_path.read_text(encoding="utf-8", errors="replace")
    if "<!-- AUTO-GEN:START -->" in existing and "<!-- AUTO-GEN:END -->" in existing:
        return {"status": "already-migrated", "matrix": str(matrix_path)}

    body = existing.rstrip() + "\n"
    migrated = (
        f"{AUTO_GEN_START}\n"
        f"{body}"
        f"{AUTO_GEN_END}\n"
    )

    result = {
        "status": "wrapped",
        "matrix": str(matrix_path),
        "overlay": str(overlay_path),
        "overlay_created": not overlay_path.exists(),
        "lines_added": 2,  # the two sentinel lines
        "bytes_before": len(existing),
        "bytes_after": len(migrated),
    }

    if not dry_run:
        matrix_path.write_text(migrated, encoding="utf-8")
        if not overlay_path.exists():
            overlay_path.write_text(
                f'schema: {OVERLAY_SCHEMA}\n# Manual overrides. '
                f'Re-run `migrate-trace-overlay` if you add more.\n',
                encoding="utf-8",
            )

    return result
