"""One log file, one row shape (Round 50 站0).

`.methodology/sessions_spawn.log` has two writers:

  core/sessions_spawn_logger.py + core/agent_spawner.py   (the Python side)
  the `__dispatchLog.push({...})` calls generated by
  scripts/workflowgen/spec_shared.py, flushed through
  `harness_cli.py log-dispatch --batch`                    (the workflow side)

Measured 2026-08-13 on a full P1–P8 run: 292 rows, 162 from the Python side
and 116 from the workflow side, with five fields in common. Every field
Round 14 站0 added so a run's cost could be answered — `total_cost_usd`,
`num_turns`, `usage`, `duration_api_ms` — exists on the Python rows only.
`run-report` aggregates the file as one population, so its convergence
metrics divide by a denominator mixing two row shapes that are not
comparable.

Neither writer is wrong on its own; there was simply no place where the row
shape was written down once. These tests are that place's contract.
"""

from __future__ import annotations

import re
from pathlib import Path

from core.spawn_log_schema import (
    OPTIONAL_FIELDS,
    REQUIRED_FIELDS,
    validate_row,
)

REPO = Path(__file__).resolve().parents[1]


def test_required_and_optional_do_not_overlap():
    assert not (REQUIRED_FIELDS & OPTIONAL_FIELDS)


def test_a_python_side_row_validates():
    row = {
        "timestamp": "2026-08-13T09:20:10.399969+00:00",
        "role": "developer", "task": "FR-01 TDD-GREEN", "session_id": "abc",
        "status": "complete", "phase": 3, "fr_id": "FR-01", "exit_code": 0,
        "duration_seconds": 12.5, "total_cost_usd": 0.42, "num_turns": 18,
    }
    assert validate_row(row) == []


def test_a_workflow_side_row_validates():
    row = {
        "timestamp": "2026-08-12T11:16:37.412213+00:00",
        "role": "sbr-1-r1", "task": "", "session_id": "",
        "status": "complete", "phase_label": "P1 · B Review",
        "substrate": "workflow", "reply_chars": 5881,
    }
    assert validate_row(row) == []


def test_an_unknown_field_is_reported():
    """A writer that invents a field must be told, not silently accepted.

    This is the whole point of having the shape in one place: the next field
    someone adds on one side becomes visible to the other.
    """
    row = {
        "timestamp": "2026-08-13T09:20:10+00:00", "role": "r", "task": "",
        "session_id": "", "status": "complete", "kost_usd": 0.42,
    }
    problems = validate_row(row)
    assert any("kost_usd" in p for p in problems), problems


def test_a_row_missing_a_required_field_is_reported():
    row = {"role": "r", "task": "", "session_id": "", "status": "complete"}
    problems = validate_row(row)
    assert any("timestamp" in p for p in problems), problems


def test_the_generated_workflow_writer_emits_only_known_fields():
    """The JS side is generated; its field names must come from the same list.

    Reads the shipped workflow rather than the generator, because the shipped
    file is what runs (Round 36: the delivered copy is the one that counts).
    """
    js = (REPO / ".claude" / "workflows" / "run-all.js").read_text(encoding="utf-8")
    # Rows reach the file as a `log-dispatch --batch` payload; the workflow
    # builds each one here.
    blocks = re.findall(r"__dispatchLog\.push\(\s*\{(.*?)\}\s*\)", js, re.S)
    assert blocks, "no __dispatchLog.push call found in the shipped run-all.js"
    known = REQUIRED_FIELDS | OPTIONAL_FIELDS
    for block in blocks:
        for key in re.findall(r"(\w+)\s*:", block):
            assert key in known, (
                f"the generated workflow writes {key!r} into sessions_spawn.log, "
                f"and core/spawn_log_schema.py has never heard of it"
            )
