"""
Tests for load-context P1 fallback (bug #2 fix).

Bug discovered during integration-test E2E: load-context reads fr_ids from
quality_manifest.json, but that file is generated by HarnessBridge at P2 exit.
At P1 entry, the manifest does not exist, and load-context returned fr_ids=[].
The orchestrator (P1) could not enumerate FR scope and would either guess or
refuse to start. Workaround was a manual quality_manifest.json, which is
fragile and undocumented.

Fix: when quality_manifest.json is missing or empty, load-context falls back
to extracting FR headers from the canonical spec declared in PROJECT_BRIEF.md.
Two PROJECT_BRIEF.md layouts are supported:
  (a) inline:     `canonical_spec: SPEC.md`
  (b) heading:    `## canonical_spec\nSPEC.md\n`

Reference: integration-test/AUDIT_LOG entry 2026-06-15-bug-2
"""
import json
import subprocess
import sys
from pathlib import Path

import pytest


HARNESS_CLI = Path(__file__).resolve().parent.parent / "harness_cli.py"


def _run_load_context(project_dir: Path, env: dict) -> dict:
    """Invoke load-context --json and parse the result."""
    import os
    full_env = {**os.environ, **env, "PYTHONPATH": str(project_dir / "harness")}
    proc = subprocess.run(
        [sys.executable, str(HARNESS_CLI), "load-context",
         "--phase", "1", "--project", str(project_dir), "--json"],
        cwd=str(project_dir), env=full_env, capture_output=True, text=True,
    )
    assert proc.returncode == 0, f"load-context failed: {proc.stderr}"
    return json.loads(proc.stdout)


@pytest.fixture
def tmp_project(tmp_path: Path) -> Path:
    """Minimal integration-test-shaped project: SPEC.md + PROJECT_BRIEF.md."""
    (tmp_path / "harness").mkdir()  # satisfy PYTHONPATH=harness
    (tmp_path / ".methodology").mkdir()
    (tmp_path / "01-requirements").mkdir()
    (tmp_path / "02-architecture").mkdir()
    (tmp_path / "03-development").mkdir()
    (tmp_path / "04-testing").mkdir()
    (tmp_path / "05-verification").mkdir()
    (tmp_path / "06-quality").mkdir()
    (tmp_path / "07-risk").mkdir()
    (tmp_path / "08-config").mkdir()
    return tmp_path


def test_p1_fallback_to_brief_inline_format(tmp_project: Path) -> None:
    """P1 cold start: no manifest, brief uses inline `canonical_spec: SPEC.md`."""
    (tmp_project / "SPEC.md").write_text(
        "# SPEC\n\n### FR-01: alpha\n\n### FR-02: beta\n\n### FR-03: gamma\n",
        encoding="utf-8",
    )
    (tmp_project / "PROJECT_BRIEF.md").write_text(
        "# Brief\n\ncanonical_spec: SPEC.md\n\n## Intent\nfoo\n",
        encoding="utf-8",
    )
    result = _run_load_context(tmp_project, env={})
    assert result["fr_ids"] == ["FR-01", "FR-02", "FR-03"]
    assert "PROJECT_BRIEF.md::canonical_spec" in result["fr_id_source"]
    assert "P1 fallback" in result["fr_id_source"]


def test_p1_fallback_to_brief_heading_format(tmp_project: Path) -> None:
    """P1 cold start: brief uses `## canonical_spec\\nSPEC.md` heading."""
    (tmp_project / "SPEC.md").write_text(
        "# SPEC\n\n### FR-01: a\n\n### FR-02: b\n",
        encoding="utf-8",
    )
    (tmp_project / "PROJECT_BRIEF.md").write_text(
        "# Brief\n\n## canonical_spec\nSPEC.md\n\n## Intent\nbar\n",
        encoding="utf-8",
    )
    result = _run_load_context(tmp_project, env={})
    assert result["fr_ids"] == ["FR-01", "FR-02"]
    assert "PROJECT_BRIEF.md::canonical_spec" in result["fr_id_source"]


def test_p2_plus_uses_manifest_when_present(tmp_project: Path) -> None:
    """When manifest exists with fr_ids, it takes precedence (no fallback)."""
    (tmp_project / "SPEC.md").write_text("# SPEC\n\n### FR-99: irrelevant\n", encoding="utf-8")
    (tmp_project / "PROJECT_BRIEF.md").write_text(
        "canonical_spec: SPEC.md\n", encoding="utf-8"
    )
    (tmp_project / ".methodology" / "quality_manifest.json").write_text(
        json.dumps({"fr_ids": ["FR-01", "FR-02"], "gate_results": {}}),
        encoding="utf-8",
    )
    result = _run_load_context(tmp_project, env={})
    assert result["fr_ids"] == ["FR-01", "FR-02"]
    assert result["fr_id_source"] == "quality_manifest.json"


def test_p1_no_brief_no_manifest_returns_empty(tmp_project: Path) -> None:
    """No brief, no manifest → fr_ids=[], fr_id_source='none' (no error)."""
    result = _run_load_context(tmp_project, env={})
    assert result["fr_ids"] == []
    assert result["fr_id_source"] == "none"


def test_p1_brief_but_canonical_spec_missing(tmp_project: Path) -> None:
    """Brief references non-existent spec → fall through to fr_ids=[], no crash."""
    (tmp_project / "PROJECT_BRIEF.md").write_text(
        "canonical_spec: nonexistent.md\n", encoding="utf-8"
    )
    result = _run_load_context(tmp_project, env={})
    assert result["fr_ids"] == []
    assert result["fr_id_source"] == "none"
