"""
Tests for load-context P1 fallback (bug #2 fix).

Bug discovered during integration-test E2E: load-context reads fr_ids from
quality_manifest.json, but that file is generated by HarnessBridge at P2 exit.
At P1 entry, the manifest does not exist, and load-context returned fr_ids=[].
The orchestrator (P1) could not enumerate FR scope and would either guess or
refuse to start. Workaround was a manual quality_manifest.json, which is
fragile and undocumented.

Fix: when quality_manifest.json is missing or empty, load-context falls back
to extracting FR headers from the canonical spec.

Round 84: the canonical spec is `ProjectLayout.spec_path` (project-root
SPEC.md). It used to be whatever PROJECT_BRIEF.md's `canonical_spec:` field
declared, in either of two layouts — a variable that all eleven corpus
projects set to the same value the framework already stated five other ways.

Reference: integration-test/AUDIT_LOG entry 2026-06-15-bug-2
"""
import json
import subprocess
import sys
from pathlib import Path

import pytest


HARNESS_CLI = Path(__file__).resolve().parent.parent / "harness_cli.py"


def _run_load_context(project_dir: Path, env: dict) -> dict:
    """Invoke load-context --json and parse the result."""
    import os
    full_env = {**os.environ, **env, "PYTHONPATH": str(project_dir / "harness")}
    proc = subprocess.run(
        [sys.executable, str(HARNESS_CLI), "load-context",
         "--phase", "1", "--project", str(project_dir), "--json"],
        cwd=str(project_dir), env=full_env, capture_output=True, text=True,
    )
    assert proc.returncode == 0, f"load-context failed: {proc.stderr}"
    return json.loads(proc.stdout)


@pytest.fixture
def tmp_project(tmp_path: Path) -> Path:
    """Minimal integration-test-shaped project (SPEC.md written per-test)."""
    (tmp_path / "harness").mkdir()  # satisfy PYTHONPATH=harness
    (tmp_path / ".methodology").mkdir()
    (tmp_path / "01-requirements").mkdir()
    (tmp_path / "02-architecture").mkdir()
    (tmp_path / "03-development").mkdir()
    (tmp_path / "04-testing").mkdir()
    (tmp_path / "05-verification").mkdir()
    (tmp_path / "06-quality").mkdir()
    (tmp_path / "07-risk").mkdir()
    (tmp_path / "08-config").mkdir()
    return tmp_path


def test_p1_fallback_reads_the_canonical_spec(tmp_project: Path) -> None:
    """P1 cold start: no manifest → FR ids come from project-root SPEC.md."""
    (tmp_project / "SPEC.md").write_text(
        "# SPEC\n\n### FR-01: alpha\n\n### FR-02: beta\n\n### FR-03: gamma\n",
        encoding="utf-8",
    )
    result = _run_load_context(tmp_project, env={})
    assert result["fr_ids"] == ["FR-01", "FR-02", "FR-03"]
    assert "SPEC.md" in result["fr_id_source"]
    assert "P1 fallback" in result["fr_id_source"]


def test_p1_fallback_ignores_a_spec_outside_the_project_root(
    tmp_project: Path,
) -> None:
    """Round 84: the location is the constant, not a declared path.

    A SPEC.md under a phase directory is not the canonical spec; before this
    round a PROJECT_BRIEF.md field could point the fallback at any file.
    """
    (tmp_project / "01-requirements" / "SPEC.md").write_text(
        "# SPEC\n\n### FR-01: alpha\n", encoding="utf-8",
    )
    result = _run_load_context(tmp_project, env={})
    assert result["fr_ids"] == []
    assert result["fr_id_source"] == "none"


def test_p2_plus_uses_manifest_when_present(tmp_project: Path) -> None:
    """When manifest exists with fr_ids, it takes precedence (no fallback)."""
    (tmp_project / "SPEC.md").write_text("# SPEC\n\n### FR-99: irrelevant\n", encoding="utf-8")
    (tmp_project / ".methodology" / "quality_manifest.json").write_text(
        json.dumps({"fr_ids": ["FR-01", "FR-02"], "gate_results": {}}),
        encoding="utf-8",
    )
    result = _run_load_context(tmp_project, env={})
    assert result["fr_ids"] == ["FR-01", "FR-02"]
    assert result["fr_id_source"] == "quality_manifest.json"


def test_p1_no_spec_no_manifest_returns_empty(tmp_project: Path) -> None:
    """No SPEC.md, no manifest → fr_ids=[], fr_id_source='none' (no error)."""
    result = _run_load_context(tmp_project, env={})
    assert result["fr_ids"] == []
    assert result["fr_id_source"] == "none"


def test_p1_spec_without_fr_headings_returns_empty(tmp_project: Path) -> None:
    """A SPEC.md with no `### FR-NN:` anchors falls through, no crash."""
    (tmp_project / "SPEC.md").write_text(
        "# SPEC\n\nProse only, no requirement anchors.\n", encoding="utf-8",
    )
    result = _run_load_context(tmp_project, env={})
    assert result["fr_ids"] == []
    assert result["fr_id_source"] == "none"


# ── Round 65 站2: where the tests are, said once ────────────────────────────

def test_load_context_reports_the_resolved_test_and_coverage_targets(tmp_project):
    """The Phase 4 coverage prompt reads these instead of naming paths.

    `b12ff21` wrote `03-development/tests/` and `--cov=03-development/src`
    into the prompt. Those are `ProjectLayout`'s FIRST choice, not its only
    one: a project with no `03-development/` directory keeps its tests at the
    root, the command exits 4 collecting nothing, `coverage_raw.txt` is
    written empty — and the same prompt tells the agent that a mismatch
    against the framework's own measurement is reported CRITICAL. Round 32
    站3 removed the fifth hand-rolled copy of this probe from
    `harness/tool_runners.py`; the prompt was a sixth, out of reach of every
    import that had unified the other five.
    """
    from core.quality_gate.test_suite_run import resolve_targets

    ctx = _run_load_context(tmp_project, {})
    assert (ctx["test_target"], ctx["cov_target"]) == resolve_targets(tmp_project)


def test_the_reported_targets_follow_the_project_not_the_default_layout(tmp_path):
    """A root-layout project must be told `tests`, not `03-development/tests`."""
    (tmp_path / "tests").mkdir()
    (tmp_path / "src").mkdir()
    (tmp_path / ".methodology").mkdir()
    ctx = _run_load_context(tmp_path, {})
    assert ctx["test_target"] == "tests"
    assert ctx["cov_target"] == "src"


def test_an_explicit_coveragerc_source_reaches_the_prompt(tmp_path):
    """`.coveragerc [run] source` wins for --cov, as it does at Gate 3."""
    (tmp_path / "03-development" / "tests").mkdir(parents=True)
    (tmp_path / "03-development" / "src").mkdir(parents=True)
    (tmp_path / ".methodology").mkdir()
    (tmp_path / ".coveragerc").write_text(
        "[run]\nsource = 03-development/src/pkg\n", encoding="utf-8")
    ctx = _run_load_context(tmp_path, {})
    assert ctx["test_target"] == "03-development/tests"
    assert ctx["cov_target"] == "03-development/src/pkg"


# ── Round 85 站2: how long to wait for run-fr-step, said once ───────────────

def test_load_context_reports_the_poll_budget_the_fr_loop_will_need(tmp_project):
    """The per-FR GATE1 prompts read these instead of naming a cap.

    Same defect one layer over from the two targets above: `b18daa62` shipped
    "cap 96 polls / ~48min, comfortably above the ~2400s worst case", and
    2880s does not cover 4800s. The prose it was calibrated against counted
    the CODE-FIX spawn per fix round and missed the full GATE1 re-dispatch
    that follows at the same indent (`cli/fr_cmds.py`, the spawn after the
    `is_s3` else-branch).
    """
    from cli.fr_cmds import fr_step_poll_plan

    ctx = _run_load_context(tmp_project, {})
    cap, interval = fr_step_poll_plan(tmp_project)
    assert (ctx["fr_step_poll_cap"], ctx["fr_step_poll_interval_s"]) == (cap, interval)
    # Whatever the interval, the product must cover the default worst case:
    # _STEP_RETRY_ATTEMPTS(2) x 600 + max_fix_rounds(3) x 2 x 600.
    assert ctx["fr_step_poll_cap"] * ctx["fr_step_poll_interval_s"] >= 4800


def test_a_per_fr_timeout_override_widens_the_cap_for_the_whole_phase(tmp_path):
    """`fr_config` is per-FR; the cap is per-phase, so it must take the max.

    The override shape is the framework's own documented example
    (`cli/fr_cmds.py`: `{"fr_config": {"FR-19": {"timeout": 1200,
    "max_fix_rounds": 5}}}`). A cap computed from the defaults alone would
    kill exactly the FR that asked for more room — which is the case the
    literal cap failed at, reproduced one level up.
    """
    (tmp_path / ".methodology").mkdir()
    (tmp_path / ".methodology" / "quality_manifest.json").write_text(json.dumps(
        {"fr_config": {"FR-19": {"timeout": 1200, "max_fix_rounds": 5}}}),
        encoding="utf-8")
    ctx = _run_load_context(tmp_path, {})
    budget = ctx["fr_step_poll_cap"] * ctx["fr_step_poll_interval_s"]
    assert budget >= 2 * 1200 + 5 * 2 * 1200, (
        "the poll cap ignores fr_config — a phase-wide number computed from "
        "the defaults is below the budget an overriding FR declared"
    )
