"""The nine checks advance-phase runs before it will move a phase.

Round 82 站2. Moved out of cli/phase_cmds.py verbatim — Round 81 站6 extracted
these nine statement runs out of `_advance_prechecks` (818 -> 244 lines) and
left them in the same file, which is why that file GREW by 243 while the
function shrank by 574. This is the other half: the runs leave, and
`_advance_prechecks` keeps its nine call sites unchanged.

The bodies here are byte-identical to what they replaced, which
tests/test_god_file_split_safety.py checks by AST source-segment sha256 and
tests/test_extraction_moved_not_rewrote.py checks against the pre-extraction
recording of phase_cmds.py. Neither golden was regenerated for this move; a
fingerprint that did not change IS the claim.

`_MYPY_EXCLUDE_ARGS` travels with them: it is the only name in phase_cmds these
nine read, its single call site is in `_precheck_p3_security_and_quality`, and
leaving it behind would mean importing back into phase_cmds — a cycle that
resolves only by line order. cli/phase_cmds.py re-exports both it and the nine,
so every existing caller, every `monkeypatch.setattr(phase_cmds, ...)` and
tests/test_mypy_excludes_harness_submodule.py's import keep working.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

from cli import _shared
from cli.advance_checks import _check_gate1_live_coverage, _regen_traceability_views
from cli.handoff_validators import _resolve_fr_ids_from_manifest
from core.atomic_io import atomic_write_json, file_lock, state_lock_path
from core.evidence_retention import ADVANCE_CLEARED_DIRS, cited_evidence_dir
from core.harness_config import get_timeout, get_value
from core.phase_topology import ADVANCE_GATE1_CHECK_PHASES
from core.quality_gate import agent_b_approvals, gate1_evidence, spec_coverage
from core.quality_gate.legal_artifacts import PHASE_DELIVERABLES
from core.state_io import load_state
from core.utils.delivery_scope import BACKUP_SUFFIXES
from core.utils.project_layout import ProjectLayout


# Round 43: the harness submodule is always mounted at this fixed path
# (init-project / submodule_guard.py both hardcode "harness" too — there is
# no per-project override anywhere), and it ships its own test fixtures
# shaped like the framework's canonical `03-development/` layout. mypy has
# no default boundary at a nested `.git` the way ruff's file-walker does, so
# `mypy .` from a consumer project's root walks straight into
# harness/tests/fixtures/.../03-development/tests/conftest.py and collides
# with the consumer's own 03-development/tests/conftest.py ("Duplicate
# module named conftest") the moment the latter exists — aborting the whole
# type-check before it examines anything else. Named here so the exclusion
# is independently testable rather than an inline literal in the
# subprocess.run() call below.
_MYPY_EXCLUDE_ARGS = ["--exclude", "^harness/"]


def _precheck_cleared_dir_evidence(_cleared_reads, project) -> "int | None":
    """Cleared dir evidence — extracted verbatim from `_advance_prechecks`.

    Round 81 站6. See the note above the first `_precheck_*` for what
    makes this a move rather than a rewrite.
    """
    if _cleared_reads:
        _cited = cited_evidence_dir(project).relative_to(project)
        print(
            f"\n[BLOCKED] {len(_cleared_reads)} delivered test path(s) read from "
            f"a directory advance-phase deletes at every transition "
            f"({', '.join(ADVANCE_CLEARED_DIRS)}):"
        )
        for _row in _cleared_reads:
            print(f"  - {_row['path']}:{_row['line']}  {_row['literal']}")
        print(
            f"  Those tests pass now and skip after this advance, which turns "
            f"the requirements they witness PARTIAL and refuses the NEXT "
            f"advance.\n"
            f"  Fix: move the evidence a later phase must still read to "
            f"{_cited}/ (or anywhere outside the cleared list) and update the "
            f"path in each line above — .methodology/ is committed and "
            f"survives the transition. Then re-run advance-phase."
        )
        return 21
    # Generated by the extraction, not moved with the run: mypy
    # requires the fall-through path to be explicit.
    return None


def _precheck_backup_artifacts(_backups) -> "int | None":
    """Backup artifacts — extracted verbatim from `_advance_prechecks`.

    Round 81 站6. See the note above the first `_precheck_*` for what
    makes this a move rather than a rewrite.
    """
    if _backups:
        print(
            f"\n[BLOCKED] {len(_backups)} tool leftover(s) in the delivered "
            f"tree — files ending {', '.join(BACKUP_SUFFIXES)} are an editor's "
            f"or a mutation runner's copy, not a deliverable:"
        )
        for _b in _backups:
            print(f"  - {_b}")
        print(
            "  They are scored, mutated and shipped as if they were source. "
            "Fix: delete them (or gitignore them if a tool keeps rewriting "
            "them), then re-run advance-phase."
        )
        return 21
    # Generated by the extraction, not moved with the run: mypy
    # requires the fall-through path to be explicit.
    return None


def _precheck_manifest_and_p1_baselines(_mi, completed_phase, project) -> "int | None":
    """Manifest and p1 baselines — extracted verbatim from `_advance_prechecks`.

    Round 81 站6. See the note above the first `_precheck_*` for what
    makes this a move rather than a rewrite.
    """
    if not _mi.get("passed"):
        print(
            "\n[BLOCKED] advance-phase: quality_manifest.json is structurally "
            "corrupt — refusing to commit it.\n"
            f"  Detected: {_mi.get('reason') or _mi.get('issues') or 'see the check output above'}\n"
            "  Fix: verify HEAD's copy is healthy, then restore it:\n"
            "    git show HEAD:.methodology/quality_manifest.json | head -40\n"
            "    git checkout HEAD -- .methodology/quality_manifest.json\n"
            "  Then merge this phase's gate result back into gate_results and "
            "re-run advance-phase."
        )
        return 27

    # ── P1 exit: SRS.md's own NFR vocabulary must be legal ───────────
    # Round 33 站3. SRS.md states `type:` and `dimension:`; sab_parser is the
    # only thing in the tree that enforces the first, and it runs in Phase 2 —
    # by which point the value is inside an approved, verbatim-transcribe
    # upstream deliverable and the two phases cannot converge (measured: five
    # B-review rounds to the HR-12 hard cap). Phase 1's B-checklist asks the
    # agent to check this; that leaves the verdict with the party being
    # judged. First, because a vocabulary error makes every downstream reading
    # of this file wrong and the fix is one word in one file.
    if completed_phase == 1:
        from cli.exit_codes import EX_ADVANCE_SRS_VOCABULARY_ILLEGAL
        from core.quality_gate.srs_nfr_validate import illegal_nfr_vocabulary

        _vocab = illegal_nfr_vocabulary(project)
        if _vocab:
            print(
                "\n[BLOCKED] SRS.md's machine-readable NFR block uses a "
                "vocabulary the framework does not accept:\n  "
                + "\n  ".join(_vocab)
                + "\n\n  Fix the values in 01-requirements/SRS.md and re-run "
                "advance-phase. Refused here rather than at Phase 2's "
                "generate_sab.py --validate, where SRS.md is already an "
                "approved upstream deliverable that SAD.md must transcribe."
            )
            return EX_ADVANCE_SRS_VOCABULARY_ILLEGAL

    # ── P1 checksum: TEST_INVENTORY.yaml baseline ────────────────────
    if completed_phase == 1:
        inventory_path = project / "TEST_INVENTORY.yaml"
        if inventory_path.exists():
            import hashlib
            _cksum = hashlib.sha256(inventory_path.read_bytes()).hexdigest()
            _state_path = project / ".methodology" / "state.json"
            try:
                with file_lock(state_lock_path(_state_path.parent.parent)):
                    _state = load_state(project, lenient=True)
                    _state["test_inventory_checksum"] = _cksum
                    atomic_write_json(_state_path, _state)
                    print(f"  [D4] TEST_INVENTORY.yaml checksum: {_cksum[:12]}...")
            except OSError as _e:
                print(f"  [WARN] Could not write test_inventory_checksum: {_e}")
    # Generated by the extraction, not moved with the run: mypy
    # requires the fall-through path to be explicit.
    return None


def _precheck_per_fr_gate1_and_phase_truth(_fr_ids_for_finalize, _invalid_finalize, _missing_finalize, completed_phase, project) -> "int | None":
    """Per fr gate1 and phase truth — extracted verbatim from `_advance_prechecks`.

    Round 81 站6. See the note above the first `_precheck_*` for what
    makes this a move rather than a rewrite.
    """
    if completed_phase >= 3 and _fr_ids_for_finalize:
        _missing_fr_finalize: list[str] = []
        for _frid in _fr_ids_for_finalize:
            # v2.13: pass completed_phase so the path matches finalize-gate's
            # per-phase write (Bug #121).
            _fs = _shared._finalize_sentinel_path(project, 1, _frid, phase=completed_phase)
            if _fs.exists():
                _invalid_finalize.extend(gate1_evidence.verify_finalize_evidence(
                    project, 1, completed_phase, _frid,
                ))
            if not _fs.exists():
                # DELTA auto-skip exemption: if no code changed since last Gate 1,
                # the per-FR finalize step was never called (correctly). Skip check
                # for FRs where code hasn't changed — same logic as _check_gate1_live_coverage.
                try:
                    # No phase= here on purpose: this exemption checks whether code
                    # changed since the LAST Gate 1 PASS from ANY earlier phase (DELTA
                    # carry-forward semantics) — completed_phase's own sentinel was
                    # just proven absent above, so scoping to completed_phase would
                    # always find nothing and defeat the exemption.
                    if not gate1_evidence.fr_code_changed_since_last_gate1(_frid, project):
                        continue
                except Exception as exc:
                    print(f"[WARN] advance-phase: DELTA auto-skip check for {_frid} "
                          f"failed, treating as changed (finalize still required): {exc}",
                          file=sys.stderr)
                _missing_fr_finalize.append(_frid)
                _ = None  # appease pyright
        if _missing_fr_finalize:
            _missing_finalize.append(
                f"Gate 1 per-FR ({len(_missing_fr_finalize)} FRs): "
                + ", ".join(_missing_fr_finalize[:5])
                + (f" +{len(_missing_fr_finalize)-5} more" if len(_missing_fr_finalize) > 5 else "")
            )
    if _missing_finalize:
        print(
            "\n[BLOCKED] finalize-gate not called for required gate(s):\n"
            + "".join(f"  ✗ {m}\n" for m in _missing_finalize)
            + "\n  The agent must call finalize-gate (with S3/S4 cross-validation)\n"
            + "  before advance-phase. Fabricating gate{N}_result.json or\n"
            + "  quality_manifest.json without finalize-gate is not permitted.\n"
            + "  Run: python3 harness_cli.py finalize-gate --gate <N> --phase <P> --project ."
        )
        return 17

    if _invalid_finalize:
        # A present-but-unbacked receipt is a stronger signal than a missing
        # one: something wrote the proof without doing the work. Same exit
        # code — the remedy is identical (run the real finalize-gate) — but
        # the message names what was found rather than what was absent.
        print(
            "\n[BLOCKED] finalize-gate receipt(s) present but not backed by the\n"
            "          registries finalize-gate writes alongside them:\n"
            + "".join(f"  ✗ {m}\n" for m in _invalid_finalize)
            + "\n  finalize-gate writes the gate timestamp, the Gate 1 score and the\n"
            "  receipt in that order, so a receipt without the first two was not\n"
            "  written by finalize-gate. Re-run it for the gate(s) named above."
        )
        return 17

    # ── Milestone-push precondition (Phase 3 only) ────────────────────
    # advance-phase is the FSM's authoritative gate: any path that reaches
    # it (including a session resuming after an interruption, or a human
    # running it standalone) must be held to the same bar as the SOP's own
    # push-milestone --type p3-post-gate2 step. Without this, Phase 3 can
    # exit to Phase 4 with the PUSH ③/④/⑤ milestone checkpoints never
    # having been pushed — the quality-evidence checks above (finalize-gate
    # sentinels, Phase Truth) do not cover this, and previously nothing did.
    # Reuses the same precondition push-milestone p3-post-gate2 and
    # validate-handoff --from-phase 3 already enforce (_shared.py), so all
    # three call sites stay in sync on a single definition.
    if completed_phase == 3:
        _fr_ids_for_milestone = _resolve_fr_ids_from_manifest(project)
        _milestone_errors = _shared._validate_p3_post_gate2_precondition(
            project, _fr_ids_for_milestone
        )
        if _milestone_errors:
            print(
                "\n[BLOCKED] Phase 3 milestone precondition not met "
                "(push-milestone --type p3-post-gate2 requirements):\n"
                + "".join(f"  ✗ {m}\n" for m in _milestone_errors)
                + "\n  Run: python3 harness_cli.py push-milestone --type p3-post-gate2 "
                f"--project . --fr-ids {','.join(_fr_ids_for_milestone)}"
            )
            return 12

    # ── Gate 1 per-FR coverage check (FR-loop phases only) ───────────
    if completed_phase in ADVANCE_GATE1_CHECK_PHASES:
        _rc = _check_gate1_live_coverage(project, completed_phase)
        if _rc != 0:
            return _rc

    # ── Phase Truth check (HR-11 ≥90%) ────────────────────────────────
    if completed_phase >= 3:
        try:
            from core.quality_gate.phase_truth_verifier import PhaseTruthVerifier
            verifier = PhaseTruthVerifier(str(project), completed_phase)
            truth_result = verifier.verify()
            if not truth_result["passed"]:
                score = truth_result.get("total_score", 0)
                print(f"\n[BLOCKED] Phase {completed_phase} truth = {score:.0f}% < 90% (HR-11)")
                print("  Fix gaps first, then re-run advance-phase.")
                return 11
            else:
                score = truth_result.get("total_score", 0)
                print(f"  [HR-11] Phase Truth = {score:.0f}% ≥ 90% ✓")
        except ImportError:
            print("  [WARN] PhaseTruthVerifier not available — skipping HR-11 check")
        except Exception as e:
            print(f"\n  [BLOCKED] Phase Truth check failed with unexpected error: {e}")
            print(
                "  Fix: investigate the exception above, then re-run:\n"
                f"    python harness_cli.py advance-phase --completed-phase "
                f"{completed_phase} --project {project}"
            )
            return 11
    # Generated by the extraction, not moved with the run: mypy
    # requires the fall-through path to be explicit.
    return None


def _precheck_early_stage_pass(_early_sp_path, completed_phase, project) -> None:
    """Early stage pass — extracted verbatim from `_advance_prechecks`.

    Round 81 站6. See the note above the first `_precheck_*` for what
    makes this a move rather than a rewrite.
    """
    if not _early_sp_path.exists():
        _shared._generate_stage_pass(project, 4 if completed_phase >= 6 else 1, completed_phase)
        if _early_sp_path.exists():
            subprocess.run(["git", "add", str(_early_sp_path)], cwd=str(project), capture_output=True)

    # ── Always-regenerate traceability views from SSOT ───────────────
    # TRACEABILITY_MATRIX.md (and SPEC_TRACKING.md) are render-only views of the
    # live build_traceability scan — never a gate input. Refresh them here so a
    # phase advance can't leave a stale/hand-mocked matrix; staged only if
    # changed (same no-op guard as STAGE_PASS).
    #
    # Gated to completed_phase >= 3: at P1/P2, 01-requirements/TRACEABILITY_MATRIX.md
    # is the legal_artifacts.py SSOT's peer-reviewed P1 deliverable (phase1_plan.md
    # Sub-Task 3/4), not yet a "render-only view" — no code exists yet for
    # build_traceability to scan, so the regen silently replaced the approved
    # deliverable with an all-zero empty scaffold (Total Requirements: 0, every
    # SWE.3 practice FAIL) on every single P1->P2 advance. The "stale/hand-mocked
    # matrix" drift this regen guards against is a post-implementation concern
    # (matches the completed_phase >= 3 threshold already used above for
    # PhaseTruthVerifier, the first point real code exists to scan).
    if completed_phase >= 3:
        _regen_traceability_views(project)


def _precheck_deliverable_anchors(_anchor_breaks, completed_phase, project) -> "int | None":
    """Deliverable anchors — extracted verbatim from `_advance_prechecks`.

    Round 81 站6. See the note above the first `_precheck_*` for what
    makes this a move rather than a rewrite.
    """
    if _anchor_breaks:
        from cli.exit_codes import EX_ADVANCE_DELIVERABLE_ANCHOR_BROKEN

        print(
            "\n[BLOCKED] Deliverable(s) no longer start with the H1 anchor "
            "their path declares:"
        )
        for _line in _anchor_breaks:
            print(f"  - {_line}")
        print(
            "\n  The Phase 1/2 orchestrator reloads each of these with that "
            "exact prefix\n"
            "  (loadFileViaPython -> read-file --expect-prefix -> "
            "first_line.startswith).\n"
            "  A file that fails it aborts the sub-task after 3 attempts, so "
            "sealing the\n"
            "  phase now would hand the next run an artefact it cannot load.\n"
            "  Fix the first line of each file above, then re-run advance-phase.\n"
            "  If one of them is a render-only view (TRACEABILITY_MATRIX.md, "
            "SPEC_TRACKING.md),\n"
            "  the P3+ regen normally repairs it — check the "
            "[advance-phase] lines above for\n"
            "  a skipped regen (import or scan failure) rather than editing "
            "the view by hand."
        )
        return EX_ADVANCE_DELIVERABLE_ANCHOR_BROKEN

    # ── Next-phase plan: must exist before advancing (Phase 3–7) ────
    # Prevents "advance first, plan later" ordering bugs. generate-next-plan
    # must be run BEFORE advance-phase so the agent has a plan to follow.
    # Phase 1-2 use HANDOVER.md entry flow; plan generation starts at Phase 3.
    # P8→P9 is exempt: Phase 9 (Maintenance) is ticket-driven — its plan is
    # a static playbook (phase9_plan.md, generated by plan-all), and the real
    # work plan materializes per-CR via cr-open, so no pre-advance plan gate.
    if 3 <= completed_phase < 8:
        _next_phase = completed_phase + 1
        _next_plan = project / ".methodology" / f"phase{_next_phase}_plan.md"
        if not _next_plan.exists():
            print(
                f"\n[BLOCKED] Phase{_next_phase}_plan.md not found.\n"
                f"  Run generate-next-plan BEFORE advance-phase:\n"
                f"    python3 harness_cli.py generate-next-plan --phase {_next_phase}"
                f" --project .\n"
                f"  Then re-run: python3 harness_cli.py advance-phase"
                f" --completed-phase {completed_phase} --project ."
            )
            return 15
    # Generated by the extraction, not moved with the run: mypy
    # requires the fall-through path to be explicit.
    return None


def _precheck_scope_violations(_orphans, completed_phase, project) -> "int | None":
    """Scope violations — extracted verbatim from `_advance_prechecks`.

    Round 81 站6. See the note above the first `_precheck_*` for what
    makes this a move rather than a rewrite.
    """
    if _orphans:
        print(
            f"\n[BLOCKED] Scope violation: {len(_orphans)} untracked diagnostic "
            f"script(s) at the repo root:"
        )
        for _o in _orphans:
            print(f"  - {_o}")
        print(
            "  Debug/diagnostic artifacts must live under .sessi-work/tmp/ "
            "(gitignored). Move or delete them, then re-run advance-phase."
        )
        return 21

    # ── Constitution keyword scoring: demoted to on-demand (減法 T3) ──────
    # The keyword-based document scorer no longer auto-gates advance-phase
    # (previously exit 16). Evidence for the demotion: 58 fix commits of
    # false-positive tuning (the highest maintenance tax of any check), it is
    # trivially gamed by keyword-sprinkling, and every phase had already been
    # reduced to the single "correctness" dimension. Document quality is
    # carried by A/B peer review + the tool-backed Gate 2/3/4 dimensions.
    # On-demand: python harness_cli.py check-constitution --phase N --project .

    # ── Agent B approvals (P1/P2/P6) — after C1 so deliverables confirmed ──
    if completed_phase in (1, 2, 6):
        deliverable_ids = PHASE_DELIVERABLES.get(completed_phase, [])
        if deliverable_ids:
            passed_ab, report_ab = agent_b_approvals.verify_agent_b_approvals_core(
                project, completed_phase, deliverable_ids
            )
            if not passed_ab:
                print(f"\n[BLOCKED] Agent B approvals incomplete for Phase {completed_phase}:")
                print(report_ab)
                print(
                    "\n  Fix: each deliverable needs "
                    ".methodology/agent_b_approvals/<id>.json "
                    "with review_status=APPROVE and "
                    "docs_embedded containing the required source documents, "
                    "then re-run advance-phase."
                )
                return 13
            print(f"  [Agent B] Phase {completed_phase} approvals verified ✓")
    # Generated by the extraction, not moved with the run: mypy
    # requires the fall-through path to be explicit.
    return None


def _precheck_p3_criteria_review(completed_phase, project) -> "int | None":
    """P3 exit: every FR's tests were read against the requirement they verify.

    Round 87 站5, the enforcing half. The producing half is
    `harness_cli.py review-fr-tests`, which every P3 per-FR ORCH-POST runs and
    which this block names for any FR that has not.

    This runs the SAME pair of checks the producer ran —
    `verify_agent_b_approvals_core` for the approval's own shape, and
    `criteria_review.approval_defects` for what it was about — so an approval
    accepted at ORCH-POST can only fail here for a reason that arose AFTER it:
    a declared assertion edited, a declared test added or removed. That is the
    whole point of pinning them (Round 69: a verdict is not the last thing
    said about the tree unless something re-reads it).

    Measured before shipping: no corpus project is at phase 3 (they sit at 1,
    7, 8 or 9) and no project anywhere holds an `FR-*.json` approval, so this
    blocks nothing already in flight — the next project to run P3 gets the
    producer and the enforcer together.
    """
    if completed_phase != 3:
        return None
    import json

    from cli.exit_codes import EX_AGENT_B_APPROVALS_INCOMPLETE
    from core.quality_gate import criteria_review

    fr_ids = _resolve_fr_ids_from_manifest(project)
    if not fr_ids:
        return None
    problems: list[tuple[str, list[str]]] = []
    unstated: list[str] = []
    for fr_id in fr_ids:
        sources = criteria_review.review_sources(project, fr_id)
        if not sources["requirement_excerpt"]:
            # Neither SPEC.md nor SRS.md states this FR, so there is no
            # requirement for a review to compare assertions against, and a
            # block here would charge a project for a document shape nothing
            # at P3 asked it for. The neighbours in this same run degrade the
            # same way ("TEST_SPEC.md not found — skipping", "SAB.json not
            # present — skipping").
            #
            # This is not the free N/A Round 27 named: a real P3 project has
            # `### FR-XX` in SRS.md because P1's own exit gate requires SRS.md
            # and its anchor, so reaching this branch means skipping P1 — and
            # the skip is printed rather than silent.
            unstated.append(fr_id)
            continue
        approval_path = (project / ".methodology" / "agent_b_approvals" / f"{fr_id}.json")
        reasons: list[str] = []
        if not approval_path.is_file():
            # Said here rather than scraped out of the sub-report below, whose
            # bullets under "Missing approval files" are bare paths — a reason
            # has to read as one (Round 24 站1).
            reasons.append(f"no review on record ({approval_path.name} does not exist)")
            problems.append((fr_id, reasons))
            continue
        passed, report = agent_b_approvals.verify_agent_b_approvals_core(
            project, 3, [fr_id]
        )
        if not passed:
            reasons = [ln.strip() for ln in report.splitlines()
                       if ln.strip().startswith("•")] or [report.strip()]
        try:
            approval = json.loads(approval_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            reasons.append(f"approval JSON unreadable: {exc}")
            approval = None
        if isinstance(approval, dict):
            reasons += criteria_review.approval_defects(project, fr_id, approval, sources)
        if reasons:
            problems.append((fr_id, reasons))

    if unstated:
        print(
            f"  [criteria-review] no requirement text for {', '.join(unstated)} "
            "in SPEC.md or SRS.md — nothing to review these against, skipped"
        )
    if not problems:
        print(
            f"  [criteria-review] Phase 3 — "
            f"{len(fr_ids) - len(unstated)}/{len(fr_ids)} FR review(s) verified ✓"
        )
        return None

    print(
        f"\n[BLOCKED] Phase 3 criteria review incomplete for "
        f"{len(problems)}/{len(fr_ids)} FR(s). A test named after an acceptance "
        "criterion is not a test of it — one reader must have read the "
        "requirement and the assertions together, and that reading must still "
        "describe the tests on disk."
    )
    for fr_id, reasons in problems:
        print(f"  {fr_id}:")
        for r in reasons:
            print(f"    • {r.lstrip('• ')}")
        print(
            f"    → python3 harness_cli.py review-fr-tests --fr-id {fr_id} "
            f"--phase 3 --project ."
        )
    print("  Then re-run advance-phase.")
    return EX_AGENT_B_APPROVALS_INCOMPLETE


def _precheck_sab_consistency(completed_phase, project) -> "int | None":
    """Every SAB finding advance-phase can act on, not just the missing files.

    Round 98. This block used to filter `_item.actual == "not found"`, which is
    only ever true of Check 1's missing-file item: Check 3 (architecture
    violations) writes `imports X (layer Y)` and Check 2 (unregistered files)
    writes `unregistered`, so both were discarded 100% of the time under a
    headline reading "SAB architecture violations". Measured on taskq-wow: a
    tree synthesised to produce 15 CRITICAL architecture violations put 0 of
    them through the filter. With the resolver fixed (Round 98 station 1) the
    twelve corpus projects produce 147.

    Three kinds, three remedies, so they are reported apart:

      * a declared file that is not on disk — write it, or drop the declaration
      * a delivered file in no layer — register it in SAD.md §2
      * an import the dependency matrix forbids — fix the import, or the matrix

    The third carries one more fact when `sab_amender.is_fallback_placement`
    says so: the source layer in that message was chosen by amend-sab's
    fallback heuristic, not stated by the module, so the line to change may be
    in SAD.md rather than in the code. 57 of the 147 are that shape. The
    finding is still charged — 老闆's adjudication for this round — and the
    provenance is told, not discounted.

    Extracted from `_precheck_p3_security_and_quality`, which is at its
    function-size ceiling, and it is the block that had to grow.
    """
    if completed_phase < 3:
        return None
    try:
        from core.quality_gate.sab_amender import (
            is_fallback_placement,
            normalize_sab_module_to_dotted,
        )
        from detection.drift_detector import DriftDetector

        _sab_result = DriftDetector(str(project)).detect_sab_drift()
        _blocking = [_item for _item in _sab_result.drift_items
                     if _item.severity.value in ("MEDIUM", "HIGH", "CRITICAL")]
        if not _blocking:
            return None

        _missing = [i for i in _blocking if i.actual == "not found"]
        _unregistered = [i for i in _blocking if i.actual == "unregistered"]
        _arch = [i for i in _blocking
                 if i not in _missing and i not in _unregistered]

        print(f"\n[BLOCKED] SAB architecture violations — {len(_blocking)} "
              f"finding(s) between SAD.md §2's baseline and the delivered tree:")
        for _item in _missing:
            print(f"  [{_item.location}] declared, not on disk: {_item.expected}")
            print("    → Create the file OR remove its declaration from SAD.md")
        for _item in _unregistered:
            print(f"  [{_item.location}] delivered, in no SAB layer")
            print("    → Add it to a layer in SAD.md §2, then re-run "
                  "`python3 harness_cli.py amend-sab --project .`")
        _sab = {}
        if _arch:
            try:
                _sab = json.loads(
                    (Path(project) / ".methodology" / "SAB.json").read_text(
                        encoding="utf-8"))
            except Exception as _sab_read_err:
                # The findings below stand either way — this only decides
                # whether each one can say who chose its source layer.
                print(f"  [WARN] could not re-read SAB.json for placement "
                      f"provenance ({_sab_read_err}); the findings below do not "
                      f"say whether their source layer was declared or "
                      f"chosen by amend-sab's fallback")
        for _item in _arch:
            print(f"  [{_item.location}] {_item.description}")
            _mod = normalize_sab_module_to_dotted(
                str(_item.location).split(" (")[0])
            if _sab and _mod and is_fallback_placement(_sab, _mod):
                print("    ! that source layer was chosen by amend-sab's "
                      "fallback heuristic (the module's path names no declared "
                      "layer), so SAD.md §2 may be what is wrong, not the import")
            print(f"    → Fix the import OR widen {_item.expected} in SAD.md §2")
        return 12
    except ImportError:
        print("  [WARN] DriftDetector not available — skipping SAB pre-advance check")
    except Exception as _sab_err:  # pylint: disable=broad-exception-caught
        print(f"  [WARN] SAB pre-advance check error: {_sab_err}")
    return None


def _precheck_p3_security_and_quality(completed_phase, project) -> "int | None":
    """P3 security and quality — extracted verbatim from `_advance_prechecks`.

    Round 81 站6. See the note above the first `_precheck_*` for what
    makes this a move rather than a rewrite.
    """
    if completed_phase >= 3:
        # 0.1 Secrets Scanning (gitleaks)
        # Runs outside src_dir.is_dir() intentionally: gitleaks scans the whole
        # repo (docs, configs, history), not just the source tree.
        #
        # Round 30 站6 — WITHDRAWN, both halves of the reasoning were wrong.
        #
        # The plan called for excluding .sessi-work/ and __pycache__ here,
        # because taskq-advance's .gitleaksignore silences 3 findings inside
        # gitleaks' own prior report and 2 inside .pyc mirrors of a test
        # fixture. Two measurements killed it:
        #   - `--exclude-path` does not exist. gitleaks 8.30.1 `detect` takes
        #     --source/--no-git/--config/--baseline-path; path allowlists live
        #     in .gitleaks.toml, not on the command line. The flag was assumed,
        #     not checked, and it made this call exit non-zero → rc 20 "secrets
        #     detected" on 6 tests.
        #   - The invocation below never sees those paths anyway. This is git
        #     mode, which scans COMMITS: with .sessi-work/ gitignored, a probe
        #     reports "1 commits scanned, ~20 bytes" versus ~56 for the same
        #     tree under --no-git. Those .gitleaksignore entries come from the
        #     AGENT's own working-tree run, which the framework does not issue
        #     and cannot scope from here.
        # What survives is in harness_bridge: the exclusion file must be tracked
        # (Round 29) and its digest travels with the verdict (this round).
        if shutil.which("gitleaks"):
            # Round 92: a clean gitleaks run is only evidence of "no leaks"
            # if the config it resolved can catch a leak at all. Measured on
            # two corpus projects: a `.gitleaks.toml` with `[extend]` and no
            # `useDefault = true` loads ZERO rules, so this call always
            # reports "no leaks found" regardless of what is in the tree.
            from harness.tool_runners import scanner_is_alive
            _gl_dead = scanner_is_alive(str(project))
            if _gl_dead:
                print("\n[BLOCKED] Secrets Scanning (gitleaks) config does not detect anything.")
                print(f"  {_gl_dead}")
                # Round 98: this message reached an agent with nothing to act
                # on. `scanner_is_alive` reports only what the canary observed;
                # the remedy is a config line and only this site knows it.
                print("    → Add `useDefault = true` under `[extend]` in "
                      "`.gitleaks.toml`, or delete the file to fall back to "
                      "gitleaks' default ruleset, then re-run advance-phase")
                return 20
            try:
                _gl_r = subprocess.run(
                    ["gitleaks", "detect", "--source", "."],
                    cwd=str(project),
                    capture_output=True,
                    text=True,
                    timeout=get_timeout("gitleaks", project),
                )
            except subprocess.TimeoutExpired:
                print("\n[BLOCKED] Secrets Scanning (gitleaks) timed out.")
                print("  Fix: re-run `gitleaks detect --source .` manually to "
                      "see where it hangs, then re-run advance-phase.")
                return 20
            if _gl_r.returncode != 0:
                print("\n[BLOCKED] Secrets Scanning (gitleaks) failure.")
                print("  Hardcoded secrets detected in the codebase/docs.")
                print("  Fix: remove the secret(s) `gitleaks detect --source .` "
                      "flagged (or add a documented allowlist entry), then re-run.")
                return 20
        else:
            print("  [WARN] gitleaks not installed. Skipping secrets scanning.")
        # Phase-based spec-coverage thresholds (unified v2.6)
        if completed_phase >= 6:
            sc_thresh = 90.0
        elif completed_phase >= 4:
            sc_thresh = 80.0
        else:
            sc_thresh = 60.0

        # 1. pytest + 100% coverage on TDD-governed source
        from core.phase_hooks import (
            PRAGMA_NO_COVER_ALLOWLIST,
            PRAGMA_NO_COVER_GUIDANCE,
            _audit_pragma_no_cover,  # Plan E: early pragma audit before coverage gate
        )
        from core.quality_gate.test_suite_run import run_suite
        _layout = ProjectLayout(project)
        src_dir = _layout.active_src_dir
        if src_dir.is_dir():
            # ── Plan E (Round 50+): early pragma audit ───────────────────
            # Detect non-allowlist `# pragma: no cover` BEFORE coverage/lint/
            # type. Closes the d0b3b9a → 476427d oscillation deterministically
            # (a commit that adds non-allowlist pragma can no longer pass the
            # coverage gate with synthetic coverage; it fails here first).
            # Why audit not a dispatch loop: auto_fix 13 strategies retired in
            # Round 48 because LLM-written tests silently passed. A
            # deterministic grep-based reject preserves the
            # human-in-the-loop contract and avoids the retry-LLM surface.
            _pragma_findings = _audit_pragma_no_cover([str(src_dir)])
            if _pragma_findings:
                _proj_root = str(project)
                for _pf in _pragma_findings:
                    _raw = _pf["file"]
                    if _raw.startswith(_proj_root):
                        _pf["file"] = _raw[len(_proj_root):].lstrip("/")
                print(
                    f"\n[BLOCKED] Non-allowlist `# pragma: no cover` found "
                    f"({len(_pragma_findings)} occurrence(s)) before "
                    f"advance-phase commit."
                )
                for _pf in _pragma_findings[:10]:
                    print(f"  - {_pf['file']}:{_pf['line']}")
                if len(_pragma_findings) > 10:
                    print(f"  ... and {len(_pragma_findings) - 10} more")
                print(f"  {PRAGMA_NO_COVER_GUIDANCE}")
                print(
                    "  Allowed pragma exemptions: "
                    + ", ".join(PRAGMA_NO_COVER_ALLOWLIST)
                )
                # exit 9 reserved for the coverage-gate series
                # (test / coverage / pragma) — keeps ops routing consistent
                # with the existing 100% coverage BLOCK.
                return 9

            # ── Plan F (Round 50+): early phantom module check ────────────
            # Detect FR-scope modules declared in SAB but missing from
            # disk BEFORE coverage/lint/type. Closes the silent-fall-through
            # shape that `validate_fr_coverage_immediate` had with the old
            # `Optional[list[str]]` return — a phantom FR scope used to
            # report a whole-project number and silently OK a non-existent
            # deliverable. Same shape as Plan E above; deterministic
            # rejection instead of a dispatch loop (auto_fix retired the
            # fabrication strategies in Round 48 for the same reason).
            #
            # Round 78 站1: the decision is sab_amender.phantom_module_block,
            # which resolves the source directory from `project` alone. The
            # inline version here read it relative to the process's working
            # directory, and from anywhere but the project root reported every
            # registered module as phantom — measured, all nine corpus
            # projects. What is left here is the call and the message.
            from core.quality_gate.sab_amender import phantom_module_block
            _phantoms = phantom_module_block(project)
            if _phantoms:
                print(
                    f"\n[BLOCKED] Phantom modules declared in SAB but "
                    f"missing from disk ({len(_phantoms)} module(s)) "
                    f"before advance-phase commit:"
                )
                for _pm in _phantoms[:10]:
                    print(f"  - {_pm}")
                if len(_phantoms) > 10:
                    print(f"  ... and {len(_phantoms) - 10} more")
                print(
                    "  Fix: implement the missing module, or amend SAB "
                    "via `harness_cli.py amend-sab --resolve-phantom "
                    "--fr-id <FR-ID> --reason <why>`."
                )
                return 9

            # 0.2 Linting (ruff)
            if shutil.which("ruff"):
                _rf_r = subprocess.run(["ruff", "check", ".", "--extend-ignore", "RUF001,RUF002,RUF003"], cwd=str(project))
                if _rf_r.returncode != 0:
                    print("\n[BLOCKED] Linting (ruff) failure.")
                    print("  Please fix the linting errors before advancing.")
                    return 18
            else:
                print("  [WARN] ruff not installed. Skipping linting.")

            # 0.3 Type Safety (mypy)
            if shutil.which("mypy"):
                _mp_r = subprocess.run([sys.executable, "-m", "mypy", ".", "--ignore-missing-imports", *_MYPY_EXCLUDE_ARGS], cwd=str(project))
                if _mp_r.returncode != 0:
                    print("\n[BLOCKED] Type Safety (mypy) failure.")
                    print("  Please fix the type errors before advancing.")
                    return 19
            else:
                print("  [WARN] mypy not installed. Skipping type safety.")

            # Round 25: the suite runs once per advance-phase and every
            # threshold reads that one measurement. `--cov-fail-under=100` used
            # to make pytest itself render this verdict; the comparison is now
            # explicit here, against the exact percentage, so the same number
            # can also answer FrameworkEnforcer's 70/80 and Phase Truth's
            # without three more executions of the same tests.
            _suite = run_suite(project)
            if _suite.ran and not (_suite.passed and (_suite.coverage or 0.0) >= 100.0):
                if _suite.output:
                    print(_suite.output)
                print("\n[BLOCKED] TDD test/coverage failure.")
                if not _suite.passed:
                    print(f"  Tests did not pass ({_suite.reason or 'see output above'}).")
                else:
                    print(f"  Coverage {_suite.coverage:.2f}% < 100%.")
                print(f"  Fix: 100% coverage on {_suite.cov_target} required.")
                print(f"  {PRAGMA_NO_COVER_GUIDANCE}")
                print("  Allowed pragma exemptions: "
                      + ", ".join(PRAGMA_NO_COVER_ALLOWLIST))
                # P3-A: Python < 3.11 async coverage hint
                if sys.version_info < (3, 11):  # type: ignore[reportUnreachable]
                    print(
                        f"  [Python {sys.version_info.major}.{sys.version_info.minor} note] "
                        "async function bodies called via asyncio.run() may not be tracked."
                    )
                    print("  Add '# pragma: no cover' to the 'async def' line to exclude it.")
                return 9

        # 2. D4 traceability: TEST_SPEC.md → tests/ (spec-coverage — unified)
        #    TEST_SPEC.md is the single source of truth (v2.6).
        sc_rc, sc_pct = spec_coverage._run_spec_coverage_check(project, sc_thresh, verbose=True)
        if sc_rc != 0:
            print(f"\n[BLOCKED] spec-coverage {sc_pct:.1f}% < threshold {sc_thresh:.0f}%.")
            print("  Fix: implement missing test cases from TEST_SPEC.md in tests/, then re-run.")
            return 10

    # ── P2-A: SAB consistency pre-check (MEDIUM violations block advance) ────
    _sab_rc = _precheck_sab_consistency(completed_phase, project)
    if _sab_rc is not None:
        return _sab_rc

    # Round 39 Station 1b: structural SAB validation at advance-phase.
    # preflight_sab_check (phase_hooks.py:613-691) already validates per-layer
    # allowed_dependencies (lines 644-648) and module existence — but it runs
    # only via preflight_all() in cmd_run_phase:1701 (the pre-push path),
    # never at advance-phase. Without this wire, a hand-edited SAB.json or
    # one generated from a SAD.md block that slipped past the now-extended
    # validate_sab_block reaches the handover commit and only trips at pre-
    # push. Running it here surfaces the violation BEFORE commit. Phase-
    # gated the same way as the DriftDetector block above (SAB itself only
    # exists from P2 exit). Wrapped in try/except to mirror the existing
    # resilience pattern — preflight_sab_check is best-effort: an unavailable
    # preflight must not block advance.
    if completed_phase >= 3:
        # Skip when SAB.json is missing — preflight_sab_check reports
        # passed=False in that case, but at advance-phase the absence is
        # only meaningful for completed_phase >= 4 (P3 itself just generated
        # the file). At completed_phase=3 the DriftDetector block above
        # already surfaces module-existence problems; the structural
        # allowed_dependencies check is only meaningful when there is a
        # SAB to validate. Treat missing-file as the same "skipped" path
        # the preflight takes for P1/P2.
        _sab_path = project / ".methodology" / "SAB.json"
        if not _sab_path.exists():
            print("  [INFO] SAB.json not present — skipping structural pre-advance check")
        else:
            try:
                from core.phase_hooks import PhaseHooks
                _sab_hooks = PhaseHooks(
                    str(project), phase=completed_phase,
                    enable_kill_switch=False,
                    drift_threshold=get_value(project, "drift_threshold"),
                )
                _sab_preflight = _sab_hooks.preflight_sab_check()
                if not _sab_preflight.get("passed", True):
                    _violations = _sab_preflight.get("violations", [])
                    print(
                        f"\n[BLOCKED] SAB structural violations — "
                        f"{len(_violations)} issue(s):"
                    )
                    for _v in _violations[:5]:
                        print(f"  - {_v}")
                    if len(_violations) > 5:
                        print(f"  ... and {len(_violations) - 5} more")
                    print(
                        "  Fix: amend SAD.md's SAB block so every layer name "
                        "referenced by allowed_dependencies is declared under "
                        "layers: []. Re-run generate_sab.py --overwrite."
                    )
                    return 12
            except ImportError:
                print("  [WARN] PhaseHooks unavailable — skipping SAB structural pre-advance check")
            except Exception as _sab_pre_err:  # pylint: disable=broad-exception-caught
                print(f"  [WARN] SAB structural pre-advance check error: {_sab_pre_err}")
    # Generated by the extraction, not moved with the run: mypy
    # requires the fall-through path to be explicit.
    return None


def _precheck_stage_pass_staging(_existing_bytes_hash, _sp_gate, _stage_pass_path, completed_phase, project) -> "int | None":
    """Stage pass staging — extracted verbatim from `_advance_prechecks`.

    Round 81 站6. See the note above the first `_precheck_*` for what
    makes this a move rather than a rewrite.
    """
    print(
        f"  [advance-phase] Regenerating Phase{completed_phase}_STAGE_PASS.md "
        f"from quality_manifest (gate {_sp_gate})"
    )
    _shared._generate_stage_pass(project, _sp_gate, completed_phase, truth_override=True)
    # Stage only if content changed — avoids touching git index when nothing
    # actually differs from what is already committed.
    if _stage_pass_path.exists():
        try:
            _new_bytes_hash = hash(_stage_pass_path.read_bytes())
        except OSError:
            _new_bytes_hash = None
        if _new_bytes_hash != _existing_bytes_hash:
            subprocess.run(
                ["git", "add", str(_stage_pass_path)],
                cwd=str(project), capture_output=True,
            )
            print(
                f"  [STAGE_PASS] content changed → staged {completed_phase} advance commit"
            )

    return 0
