"""The advance commit: what it stages, what it refuses, and the state write.

Round 80 站7. Moved out of cli/phase_cmds.py verbatim; the bodies here are
byte-identical to the ones that were there, which
tests/test_god_file_split_safety.py asserts by AST source segment.

Six functions around one moment — the handover commit `advance-phase` makes.
`_advance_commit_targets` is the maximal set of paths it may stage,
`_uncommitted_deliverables` (with its `-z` porcelain parser) is the refusal to
record a phase on a tree git has not, `_enforcer_moved_note` explains a finding
against an artifact accepted under an older bar, and `_advance_fsm` is the
state write itself. They referenced nothing else defined in phase_cmds.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from typing import Iterator

from core.atomic_io import StateTransaction, file_lock, state_lock_path
from core.state_io import StateCorruptError, load_state
from harness.handover_generator import HandoverGenerator


def _advance_commit_targets(
    completed_phase: int,
    next_phase: int,
    manifest_regenerated: bool,
    fr_progress_exists: bool,
    gate_timestamps_exists: bool = False,
    stage_pass_exists: bool = False,
    plan_exists: bool = True,
    attestation_exists: bool = False,
    setup_cfg_written: bool = False,
) -> list[str]:
    """Files the advance-phase local commit must stage.

    Uses an explicit list (not `git add -A`) so unrelated working-tree noise is
    not swept in. fr_progress.json is rewritten by _advance_fsm during this same
    advance, so it must be staged — but only when present: pre-Gate-1 advances
    (P1->P2, P2->P3) have no fr_progress.json yet, and an explicit `git add` of a
    missing pathspec fails the whole commit.

    gate_timestamps.jsonl is functional FR-gate state (read back to verify per-FR
    gate events) that the DELTA fast-path appends within a phase; the advance
    commit sweeps its tail so it does not linger unstaged after every phase bump.
    Conditional-exists for the same missing-pathspec reason as fr_progress.json.

    00-summary/Phase{N}_STAGE_PASS.md is machine-generated by _generate_stage_pass
    on every advance-phase run (always-regenerate). It is staged here too so a
    single `git add` in the advance commit covers it — even if the earlier
    conditional git-add at line ~6372 was skipped because content matched the
    already-committed bytes.

    .methodology/trace/attestation.json mirrors the refresh-before-push pattern
    push_cmds.py already applies to push-checkpoint/push-milestone ("every push
    path is symmetric") — advance-phase was the one caller that skipped it,
    landing a handover commit with a stale attestation SHA that only surfaces
    as a blocking failure at the next P5+ pre-push.
    """
    targets = [
        ".methodology/state.json", "HANDOVER.md",
        "CLAUDE.md",
    ]
    if plan_exists:
        # Same missing-pathspec hazard as fr_progress.json below: a project
        # without the pre-generated plan file made the whole `git add` fail,
        # so the advance commit NEVER landed (caught by
        # tests/test_advance_commit_rollback.py).
        targets.append(f".methodology/phase{completed_phase}_plan.md")
    if fr_progress_exists:
        targets.append(".methodology/fr_progress.json")
    if gate_timestamps_exists:
        targets.append(".methodology/gate_timestamps.jsonl")
    if manifest_regenerated:
        targets.append(".methodology/quality_manifest.json")
    if stage_pass_exists:
        targets.append(f"00-summary/Phase{completed_phase}_STAGE_PASS.md")
    if attestation_exists:
        targets.append(".methodology/trace/attestation.json")
    if setup_cfg_written:
        # Round 30 站2: the P2→P3 handoff renders [mutmut] paths_to_mutate from
        # the SAB. Only staged when it was actually written this run — same
        # missing-pathspec hazard as the entries above, and staging an unchanged
        # file would put a no-op into every advance commit.
        targets.append("setup.cfg")
    if next_phase == 8:
        targets += ["08-config/CONFIG_RECORDS.md", "08-config/RELEASE_CHECKLIST.md"]
    return targets

def _git_head_short(project: Path) -> str:
    """`HEAD`'s short sha, or the word HEAD when git cannot answer."""
    proc = subprocess.run(
        ["git", "-C", str(project), "rev-parse", "--short", "HEAD"],
        capture_output=True, text=True,
    )
    return proc.stdout.strip() if proc.returncode == 0 and proc.stdout.strip() else "HEAD"


def _uncommitted_deliverables(
    project: Path, completed_phase: int, next_phase: int,
) -> list[str]:
    """Delivered files whose content differs from HEAD's, sorted.

    Round 44 站2. Two exemptions, both taken from an existing single source
    rather than restated here:

      * `core.utils.delivery_scope.is_harness_volatile` — append-only
        ledgers, caches, locks, `.sessi-work/`. The harness writes them by
        running; they are not the project.
      * `_advance_commit_targets` called with every optional flag on — the
        maximal set of files THIS command rewrites and stages a few hundred
        lines below. Refusing to advance because HANDOVER.md is stale would
        be unsatisfiable: regenerating it is what the advance does. Measured
        on taskq-api, `M HANDOVER.md` is its resting state.

    Everything else is content a clone will not have. That deliberately
    includes `.methodology/harness_config.json` and `.methodology/SAB.json`,
    which are scoring inputs (station 0 premise 1) and are not in the
    advance's write set.

    Empty list when git cannot answer — a check that cannot run does not
    block (the gate verdict check immediately after this one is the one that
    refuses on missing evidence).
    """
    from core.utils.delivery_scope import is_harness_volatile

    proc = subprocess.run(
        # `-uall`, not the default: git collapses an entirely untracked
        # directory into one `?? dir/` record, which then matches no
        # exemption and names no file the operator can act on. Caught by
        # tests/e2e/test_cli_journeys.py, which reported `.methodology/trace/`
        # while the file inside it is one this command stages itself.
        ["git", "-C", str(project), "status", "--porcelain", "-z", "-uall"],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        return []

    owned = set(_advance_commit_targets(
        completed_phase, next_phase,
        manifest_regenerated=True, fr_progress_exists=True,
        gate_timestamps_exists=True, stage_pass_exists=True,
        plan_exists=True, attestation_exists=True, setup_cfg_written=True,
    ))

    dirty: set[str] = set()
    for rel in _porcelain_paths(proc.stdout):
        if rel in owned or is_harness_volatile(rel):
            continue
        dirty.add(rel)
    return sorted(dirty)


def _porcelain_paths(stdout: str) -> "Iterator[str]":
    """Repo-relative paths out of `git status --porcelain -z`.

    NUL-separated so a path containing a newline cannot be read as two, and
    unquoted so a non-ASCII path is not escaped — the same reasoning as
    `core/utils/delivery_scope.py`'s `git ls-files -z`. A rename record
    carries its source path in a second NUL-terminated field, which is
    dropped: the destination is the one that has to be committed.
    """
    fields = [f for f in stdout.split("\0") if f]
    index = 0
    while index < len(fields):
        entry = fields[index]
        index += 1
        if len(entry) < 4:
            continue
        status, rel = entry[:2], entry[3:]
        if status[0] in ("R", "C"):
            index += 1        # skip the source path that follows
        yield rel


def _enforcer_moved_note(project: Path, up_to_phase: int) -> str:
    """One line naming the phases whose recorded PASS predates a rule change.

    Round 43 站4. Appended to advance-phase's obligation [BLOCKED] because
    that message is where the question arises: a finding against a Phase 1
    artifact, on a project whose Phase 1 passed five framework rounds ago,
    reads as "you broke this" when the truth may be "the bar moved". The
    data has been recorded since Round 19 站3 / Round 29 站4 and never read
    for this.

    Diagnosis only. Nothing is waived — Round 38's rule is that no threshold
    may be, and grandfathering a rule to artifacts accepted before it existed
    is the same rule inverted: the framework could then never raise its own
    bar. Empty string when there is nothing to say, so a caller can print it
    unconditionally-guarded and add no noise.
    """
    from core.harness_provenance import phase_verdict_staleness
    moved: list[str] = []
    for phase in range(1, up_to_phase + 1):
        if phase_verdict_staleness(project, phase):
            moved.append(str(phase))
    if not moved:
        return ""
    return (
        f"  [note] Phase(s) {', '.join(moved)} recorded their PASS under a "
        f"different enforcement surface than the one running now. A finding "
        f"above against one of their artifacts may be a raised bar rather "
        f"than something this session broke. It is not waived either way — "
        f"`doctor` names which paths changed.\n"
    )


def _advance_fsm(project: Path, completed_phase: int,
                 last_gate: int | None = None,
                 last_fr: str | None = None) -> None:
    """Write state.json — the single source of truth for phase state.

    Local hooks, CI, and all harness commands read .methodology/state.json::current_phase.
    No other phase storage mechanisms exist.
    """
    from datetime import datetime, timezone
    from core.fsm.fsm import validate_fsm_state, FSMError

    next_phase = completed_phase + 1

    # 1. Prepare the full write set BEFORE anything becomes visible, then
    # publish HANDOVER.md + state.json in one StateTransaction (state.json
    # LAST — it is the authoritative file, so a partial commit can never
    # claim more progress than the artifacts on disk support). This is the
    # fix for the half-state class: the old order wrote state.json first
    # and only WARNed when HANDOVER regeneration failed afterwards, leaving
    # state advanced with a stale crash-recovery document (the P8→9 crash).
    # Cross-process locked (SG-12) so a parallel _update_state_checkpoint
    # or push-milestone state-write cannot corrupt the file.
    state_path = project / ".methodology" / "state.json"
    state_path.parent.mkdir(parents=True, exist_ok=True)
    with file_lock(state_lock_path(project)):
        existing_state = "INIT"
        state_data: dict = {}
        if state_path.exists():
            try:
                state_data = load_state(project)
            except StateCorruptError as exc:
                from core.degradation_ledger import record_degradation
                record_degradation(
                    project, "phase_cmds._advance_fsm",
                    "state.json unreadable — treating FSM state as fresh (INIT) "
                    "and overwriting the file's other fields",
                    why=str(exc), owner="project"
                )
                state_data = {}
            else:
                try:
                    existing_state = validate_fsm_state(state_data.get("state", "INIT"))
                except FSMError as e:
                    print(f"\n  [FSM ERROR] {e}")
                    print("  Fix state.json manually or run `advance-phase` with a clean state.")
                    sys.exit(11)
        # Merge into the existing dict rather than replacing it — state.json also
        # carries fields this function doesn't own (phase_completed,
        # ci_readiness_ack, language, test_runner, ...); a bare
        # replacement here silently discarded them on every advance-phase call.
        state_data.update({
            "state": existing_state,
            "current_phase": next_phase,
            "last_gate": last_gate,
            "last_fr": last_fr,
            "last_update": datetime.now(timezone.utc).isoformat(),
            # P5-BUG-02: User expects phase_truth_passed to be True after advance-phase runs verify_phase_truth
            "phase_truth_passed": True,
            "last_milestone_command": f"advance-phase --completed-phase {completed_phase}",
        })

        # Render HANDOVER.md before any write — a render failure aborts the
        # advance with NOTHING published (previously it warned after state
        # was already advanced).
        gen = HandoverGenerator(project)
        handover_content = gen.render(
            checkpoint_id=f"P{next_phase}-entry-{datetime.now(timezone.utc).strftime('%Y%m%d')}",
            phase=next_phase,
            task_background=(
                f"Phase {completed_phase} completed. Advancing FSM to Phase {next_phase}."
            ),
            current_status=f"FSM advanced from Phase {completed_phase} to Phase {next_phase}.",
            next_steps=[
                f"Follow SKILL.md §0.1 Phase {next_phase} entry checklist",
                f"Read the Phase {next_phase} plan and execute",
            ],
            resume_phase=next_phase,
        )

        with StateTransaction(project) as txn:
            txn.stage_text(gen.handover_path, handover_content)
            txn.stage_json(state_path, state_data)   # authoritative file last
            txn.commit()

        # B5: Advance fr_progress.json inside the same lock so state.json and
        # fr_progress.json are always updated atomically from any reader's
        # perspective. Moving it outside created a window where another process
        # could see next_phase in state.json but the old phase in fr_progress.json.
        # SG-9: do not silently swallow exceptions — log to stderr so the
        # operator knows if state.json and fr_progress.json fall out of sync.
        # FileNotFoundError is expected for P1/P2 (no fr_progress.json yet).
        try:
            from harness.fr_progress_tracker import FRProgressTracker
            FRProgressTracker(project, phase=next_phase).advance_phase(next_phase)
        except FileNotFoundError:
            pass  # P1/P2 projects: fr_progress.json doesn't exist yet — expected.
        except Exception as exc:  # pylint: disable=broad-exception-caught
            print(
                f"  [WARN] FRProgressTracker.advance_phase failed: {type(exc).__name__}: {exc}\n"
                f"  state.json advanced to phase {next_phase}, but fr_progress.json may now\n"
                f"  be out of sync. Inspect .methodology/fr_progress.json and repair if needed.",
                file=sys.stderr,
            )
    print(f"  [FSM] state.json current_phase → {next_phase}")
    print(f"  [FSM] HANDOVER.md regenerated for Phase {next_phase}")
