"""Round 24 站2b — QUALITY_REPORT.md must agree with the gate result it claims to render.

QUALITY_REPORT.md was the one major rendered artifact with no equivalence
guard. SPEC_TRACKING has `core/traceability/spec_tracking_render.py` +
`tests/test_spec_tracking_render.py`, TRACEABILITY_MATRIX is regenerated by
advance-phase, `.methodology/trace/attestation.json` is content-fingerprinted,
and the nine workflow JS files are byte-checked by
`scripts/workflowgen/generate_workflows.py --check`. The quality report — the
document a human reads to decide whether a release is sound, and the one
Agent B peer-reviews at Gate 4 — was checked only for existence.

Observed live in the run-all-by-workflow P1-P8 validation run. `finalize-gate
--gate 4` swallowed a crash in generate_quality_report as `[WARN] ... skipped`
(cli/gate_cmds.py), so the report was never written. The agent, seeing a
missing deliverable, produced one itself: it copied gate4_result.json to a
temp workdir, rewrote `mutation_testing: {score: null}` to `0`, and re-ran the
script. The committed report carries

    | Mutation Testing | 0/100 | ✗ FAIL |

while the authoritative gate4_result.json says
`{"score": null, "excluded_by_feature_flag": true}` and the composite (97.3981)
was computed with that dimension correctly skipped. Nothing in the pipeline
noticed: the gate result was untouched so every integrity check passed, and
Agent B approved the report while describing content it does not contain.

WHY THIS VERIFIER PARSES INSTEAD OF RE-RENDERING
------------------------------------------------
It would be shorter to call `_build_dimension_table` again and diff the lines.
That check would share a source with the thing it checks: it could catch a
hand-edited file, but never a defect in the renderer itself — the exact
same-source blind spot this round exists to close. So the verifier reads the
NUMBERS out of the committed markdown and compares them to the NUMBERS in the
gate result, with no shared formatting code. It therefore also catches "the
renderer's own output is wrong".

Scope is deliberately the two SSOT-backed tables (dimensions, per-FR). The
generated-at timestamp and the CRG architecture / dead-code sections are
re-measured on every run and have no fixed authority to compare against;
asserting on them would produce a guard that fails for reasons unrelated to
correctness.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

# Displayed scores are rounded for reading (`94.3` for 94.25287356321839), so
# equality is "agrees to within a display rounding step", not float ==.
_SCORE_TOLERANCE = 0.05

_ROW = re.compile(r"^\|\s*(?P<label>[^|]+?)\s*\|\s*(?P<score>[^|]+?)\s*\|\s*(?P<status>[^|]*?)\s*\|")

_DIM_HEADER = "| Dimension | Score | Status | Detail |"
_FR_HEADER = "| FR ID | Score | Status |"


def find_latest_gate_result(project: Path) -> tuple[int, dict[str, Any]]:
    """Highest-numbered gate result, `.methodology/` before `.sessi-work/`.

    Single source for "which gate result is authoritative" —
    `scripts/generate_quality_report.py` delegates here rather than keeping a
    second copy of the search order. `.methodology/` wins because finalize-gate
    copies the result there after patching composite_score/verdict with the
    harness-computed values; the `.sessi-work/` copy still carries the agent's
    own unpatched self-assessment.
    """
    search_dirs = [project / ".methodology", project / ".sessi-work"]
    for gate_num in (4, 3, 2, 1):
        for d in search_dirs:
            path = d / f"gate{gate_num}_result.json"
            if not path.is_file():
                continue
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            if data:
                return gate_num, data
    return 0, {}


def _label_to_key(label: str) -> str:
    """`Mutation Testing` -> `mutation_testing` (inverse of the renderer's
    `key.replace("_", " ").title()`)."""
    return label.strip().lower().replace(" ", "_")


def _parse_score_cell(cell: str) -> float | None:
    """`97.0/100` -> 97.0; `N/A` -> None. Raises ValueError on anything else."""
    text = cell.strip()
    if text in ("N/A", "n/a", "—", "-"):
        return None
    return float(text.split("/")[0].strip())


def _table_rows(lines: list[str], header: str) -> list[tuple[str, str, str]]:
    """(label, score cell, status cell) for each data row under `header`."""
    try:
        start = lines.index(header)
    except ValueError:
        return []
    rows = []
    for line in lines[start + 2:]:  # skip header + separator
        if not line.startswith("|"):
            break
        m = _ROW.match(line)
        if m:
            rows.append((m["label"], m["score"], m["status"]))
    return rows


def verify_quality_report(project: Path) -> list[str]:
    """Violations where QUALITY_REPORT.md disagrees with its own sources.

    Empty list means the report agrees. A missing report is NOT reported here —
    that is the caller's deliverable check (cli/gate_cmds.py fails the gate on
    a generation failure); this function only compares a report that exists.
    """
    from core.utils.project_layout import ProjectLayout

    report_path = ProjectLayout(project).quality_report_path
    if not report_path.is_file():
        return []

    lines = report_path.read_text(encoding="utf-8").splitlines()
    gate_num, gate_result = find_latest_gate_result(project)
    violations: list[str] = []

    breakdown = gate_result.get("breakdown")
    if isinstance(breakdown, dict):
        violations.extend(_check_dimensions(lines, breakdown, gate_num, report_path))

    if (project / ".methodology" / "quality_manifest.json").is_file():
        from core.state_io import load_quality_manifest

        # lenient: a corrupt manifest is finalize-gate's own integrity check to
        # report, not this verifier's — here it just means the per-FR table has
        # no authority to be compared against.
        manifest = load_quality_manifest(project, lenient=True)
        gate1 = manifest.get("gate_results", {}).get("gate1")
        if isinstance(gate1, dict):
            violations.extend(_check_fr_rows(lines, gate1, report_path))

    return violations


def _check_dimensions(
    lines: list[str], breakdown: dict, gate_num: int, report_path: Path
) -> list[str]:
    violations: list[str] = []
    seen: set[str] = set()
    for label, score_cell, status_cell in _table_rows(lines, _DIM_HEADER):
        key = _label_to_key(label)
        if key not in breakdown:
            violations.append(
                f"{report_path.name} lists dimension '{label}' which gate{gate_num}_result.json "
                f"does not contain — the report was rendered from a different (or edited) source"
            )
            continue
        seen.add(key)
        entry = breakdown[key] if isinstance(breakdown[key], dict) else {}
        truth = entry.get("score")
        try:
            shown = _parse_score_cell(score_cell)
        except ValueError:
            violations.append(
                f"{report_path.name}: dimension '{label}' has an unparseable score cell "
                f"{score_cell!r}"
            )
            continue

        if truth is None and shown is not None:
            violations.append(
                f"{report_path.name}: '{label}' shows {score_cell.strip()} ({status_cell.strip()}) "
                f"but gate{gate_num}_result.json records score=null — a null score means NOT "
                f"MEASURED (framework-owned, or excluded by a harness_config.json feature flag), "
                f"never zero. Re-run finalize-gate to re-render; do not hand-edit either file."
            )
        elif truth is not None and shown is None:
            violations.append(
                f"{report_path.name}: '{label}' shows N/A but gate{gate_num}_result.json records "
                f"score={truth}. Re-run finalize-gate to re-render."
            )
        elif (
            truth is not None
            and shown is not None
            and abs(float(truth) - shown) > _SCORE_TOLERANCE
        ):
            violations.append(
                f"{report_path.name}: '{label}' shows {shown} but gate{gate_num}_result.json "
                f"records {truth}. Re-run finalize-gate to re-render."
            )

    missing = sorted(set(breakdown) - seen)
    if missing:
        violations.append(
            f"{report_path.name} omits dimension(s) {missing} present in "
            f"gate{gate_num}_result.json — a dimension dropped from the report is a "
            f"dimension nobody reviews. Re-run finalize-gate to re-render."
        )
    return violations


def _check_fr_rows(lines: list[str], gate1: dict, report_path: Path) -> list[str]:
    violations: list[str] = []
    for fr_id, score_cell, _status in _table_rows(lines, _FR_HEADER):
        entry = gate1.get(fr_id)
        if not isinstance(entry, dict):
            violations.append(
                f"{report_path.name} lists {fr_id} in the per-FR table, but "
                f"quality_manifest.json has no gate1 entry for it"
            )
            continue
        truth = entry.get("score")
        try:
            shown = _parse_score_cell(score_cell)
        except ValueError:
            violations.append(
                f"{report_path.name}: per-FR row {fr_id} has an unparseable score cell "
                f"{score_cell!r}"
            )
            continue
        if truth is None and shown is not None:
            violations.append(
                f"{report_path.name}: {fr_id} shows {shown} but quality_manifest.json records "
                f"score=null. Re-run finalize-gate to re-render."
            )
        elif (
            truth is not None
            and shown is not None
            and abs(float(truth) - shown) > _SCORE_TOLERANCE
        ):
            violations.append(
                f"{report_path.name}: {fr_id} shows {shown} but quality_manifest.json records "
                f"{truth}. Re-run finalize-gate to re-render."
            )
    return violations
