#!/bin/bash
# =============================================================================
# Git Hooks Setup Script
# =============================================================================
# Sets up Git Hooks for the methodology project, ensuring Phase status
# is checked before each commit.
#
# Usage:
#   bash scripts/setup-git-hooks.sh
# =============================================================================

set -e  # Exit on error

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo "=============================================="
echo "Git Hooks Setup for harness-methodology"
echo "=============================================="
echo

# Resolve git working tree
PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$PROJECT_ROOT" ]; then
    echo -e "${RED}Error: Not a Git repository${NC}"
    echo "Please run this script from within a Git repository."
    exit 1
fi

# Calculate hooks directory relative to PROJECT_ROOT
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOKS_DIR="$SCRIPT_DIR/hooks"
RELATIVE_HOOKS_DIR="${HOOKS_DIR#$PROJECT_ROOT/}"

if [ ! -d "$PROJECT_ROOT/$RELATIVE_HOOKS_DIR" ]; then
    echo -e "${RED}Error: Hooks directory not found at $RELATIVE_HOOKS_DIR${NC}"
    exit 1
fi

cd "$PROJECT_ROOT"

# Set Git core.hooksPath
git config core.hooksPath "$RELATIVE_HOOKS_DIR"

# Clean up legacy physical hooks in .git/hooks if they exist
GIT_DIR="$(git rev-parse --git-dir 2>/dev/null)"
for hook in prepare-commit-msg post-merge pre-commit pre-push; do
    if [ -f "$GIT_DIR/hooks/$hook" ]; then
        # Check if it was generated by our old script
        if grep -q "harness_cli.py" "$GIT_DIR/hooks/$hook"; then
            rm -f "$GIT_DIR/hooks/$hook"
            echo "Cleaned up legacy physical hook: .git/hooks/$hook"
        fi
    fi
done

echo -e "${GREEN}OK${NC} Set core.hooksPath to $RELATIVE_HOOKS_DIR"
echo ""
echo "=============================================="
echo -e "${GREEN}Git Hooks Setup Complete!${NC}"
echo "=============================================="
echo ""
echo "Hooks active:"
echo "  - prepare-commit-msg: Block commits if Phase not passed"
echo "  - pre-commit: Warn on uncommitted submodule edits + canonical FR-ID lint"
echo "  - post-merge: Check Phase status after merge"
echo "  - pre-push: Check before pushing"
echo ""
echo "Any future updates to $RELATIVE_HOOKS_DIR/ will apply automatically."
echo ""
