"""Gap Report Generation Module.

Generates JSON and Markdown gap reports.
"""

import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from gap_detector.parser import ParsedSpec
from gap_detector.scanner import ScannedCode
from gap_detector.detector import Gap, GapSummary


@dataclass
class ReportPaths:
    """ReportPaths component."""
    json_path: str
    md_path: str


@dataclass
class GapReportJSON:
    """GapReportJSON component."""
    generated_at: str
    spec_file: str
    implement_dir: str
    summary: dict
    gaps: list
    spec_features_count: int
    code_items_count: int


class GapReporter:
    """Reporter for generating gap reports."""

    def __init__(self, gaps, spec: ParsedSpec, code: ScannedCode, output_dir: str = "reports/") -> None:
        """Initialize instance."""
        self.gaps = gaps
        self.spec = spec
        self.code = code
        self.output_dir = output_dir

    def generate(self) -> ReportPaths:
        """Generate."""
        output_path = Path(self.output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        json_path = output_path / "gap_report.json"
        md_path = output_path / "gap_summary.md"
        self._generate_json(json_path)
        self._generate_markdown(md_path)
        return ReportPaths(json_path=str(json_path), md_path=str(md_path))

    def _compute_summary(self) -> GapSummary:
        s = GapSummary(total_gaps=len(self.gaps))
        for g in self.gaps:
            if g.gap_type == "MISSING":
                s.missing += 1
            elif g.gap_type == "INCOMPLETE":
                s.incomplete += 1
            elif g.gap_type == "ORPHANED":
                s.orphaned += 1
            if g.severity == "critical":
                s.critical += 1
            elif g.severity == "major":
                s.major += 1
            elif g.severity == "minor":
                s.minor += 1
        return s

    def _gap_to_dict(self, gap: Gap) -> dict:
        return {
            "gap_type": gap.gap_type, "spec_item": gap.spec_item,
            "code_item": gap.code_item, "spec_location": gap.spec_location,
            "code_location": gap.code_location, "severity": gap.severity,
            "reason": gap.reason, "recommended_action": gap.recommended_action,
            "downstream_missing": gap.downstream_missing
        }

    def _generate_json(self, output_path: Path) -> None:
        s = self._compute_summary()
        spec_features_count = len(self.spec.feature_items)
        code_items_count = sum(len(m.items) for m in self.code.modules)
        report = {
            "generated_at": datetime.now().isoformat(),
            "spec_file": getattr(self.spec.metadata, 'title', 'Unknown'),
            "implement_dir": "implement/",
            "summary": {"total_gaps": s.total_gaps, "missing": s.missing,
                        "incomplete": s.incomplete, "orphaned": s.orphaned,
                        "critical": s.critical, "major": s.major, "minor": s.minor},
            "gaps": [self._gap_to_dict(g) for g in self.gaps],
            "spec_features_count": spec_features_count,
            "code_items_count": code_items_count
        }
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, ensure_ascii=False)

    def _generate_markdown(self, output_path: Path) -> None:
        s = self._compute_summary()
        lines = [
            "# Gap Summary Report", "",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Spec:** {getattr(self.spec.metadata, 'title', 'Unknown')}", "",
            "## Overview", "",
            "| Metric | Value |", "|--------|-------||",
            f"| Total Gaps | {s.total_gaps} |",
            f"| MISSING | {s.missing} |",
            f"| INCOMPLETE | {s.incomplete} |",
            f"| ORPHANED | {s.orphaned} |",
            f"| Critical | {s.critical} |",
            f"| Major | {s.major} |",
            f"| Minor | {s.minor} |", "",
        ]
        missing_gaps = [g for g in self.gaps if g.gap_type == "MISSING"]
        if missing_gaps:
            lines += ["## Missing Features", "",
                      "| Feature | Location | Severity |",
                      "|---------|----------|----------|"] + [
                f"| {g.spec_item or 'N/A'} | {g.spec_location or 'N/A'} | {g.severity} |"
                for g in missing_gaps
            ] + [""]
        lines += ["", "---", "*Report generated by Gap Detection Agent*"]
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
