import subprocess
#!/usr/bin/env python3
"""
Agent-Proof Hook
================
A hook that agents cannot bypass.

Features:
1. Lives in .methodology/ (not .git/hooks/ — less obvious)
2. Core logic in Python module, hook is a thin wrapper
3. Supports Unix immutable attribute (chattr +i)
4. Periodic integrity checks
"""

import os
import sys
import hashlib
import shutil
from pathlib import Path
from typing import Optional


class AgentProofHook:
    """
    Agent-Proof Hook.

    Usage::

        hook = AgentProofHook()
        hook.install()
        hook.verify()  # Check for tampering
    """

    METHODOLOGY_DIR = ".methodology"
    HOOK_MODULE = "agent_hook_core"
    HOOK_FILE = f".methodology/agent_hook_core.py"

    WRAPPER_TEMPLATE = '''#!/usr/bin/env python3
"""
Agent-Proof Pre-Commit Hook
Generated by harness-methodology
DO NOT EDIT - CHANGES WILL BE OVERWRITTEN
"""
import sys
import os

# Ensure .methodology is on path
methodology_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '.methodology')
if methodology_dir not in sys.path:
    sys.path.insert(0, methodology_dir)

# Run core enforcement
from agent_hook_core import enforce

try:
    enforce()
    print("Agent-Proof Hook: All checks passed")
except SystemExit as e:
    sys.exit(e.code)
except Exception as e:
    print(f"Agent-Proof Hook error: {e}")
    sys.exit(1)
'''

    def __init__(self, project_root: str = None):
        self.project_root = Path(project_root) if project_root else Path.cwd()
        self.hook_path = self.project_root / ".git" / "hooks" / "pre-commit"
        self.core_path = self.project_root / self.HOOK_FILE

    def install(self, force: bool = False):
        """Install the Agent-Proof Hook."""
        print("Installing Agent-Proof Hook...")
        method_dir = self.project_root / self.METHODOLOGY_DIR
        method_dir.mkdir(exist_ok=True)
        self._install_core_module(method_dir)
        self._install_hook_wrapper(force=force)
        self._try_immutable()
        print(f"Agent-Proof Hook installed")
        print(f"  Core module: {self.core_path}")
        print(f"  Hook: {self.hook_path}")

    def _install_core_module(self, method_dir: Path):
        """Write the core enforcement module."""
        core_content = self._generate_core_module()
        core_path = method_dir / f"{self.HOOK_MODULE}.py"
        with open(core_path, "w") as f:
            f.write(core_content)
        print(f"  Core module written: {core_path}")

    def _generate_core_module(self) -> str:
        """Generate core module content."""
        return '''#!/usr/bin/env python3
"""
Agent Hook Core
===============
Core enforcement logic. Lives in .methodology/ (less obvious than .git/hooks/).
"""

import os
import re
import sys


def enforce():
    """Main enforcement function. Called by the pre-commit hook wrapper."""
    print("Agent-Proof Hook: Running checks...")

    commit_msg_file = os.environ.get("COMMIT_MSG_FILE", ".git/COMMIT_EDITMSG")

    if os.path.exists(commit_msg_file):
        with open(commit_msg_file, "r") as f:
            msg = f.read().strip()

        if not re.search(r"\\[[A-Z]+-\\d+\\]", msg):
            print("Commit message must include task ID (e.g., [TASK-123])")
            print(f"  Your message: {msg[:50]}...")
            sys.exit(1)

        print("  Task ID found in commit message")

    suspicious_env = os.environ.get("GIT_COMMAND", "")
    bypass_keywords = ["--no-verify", "--bypass", "--skip-hooks"]

    for kw in bypass_keywords:
        if kw in suspicious_env:
            print(f"Suspicious bypass keyword detected: {kw}")
            sys.exit(1)

    print("All Agent-Proof checks passed")


if __name__ == "__main__":
    enforce()
'''

    def _install_hook_wrapper(self, force: bool = False):
        """Install git hook wrapper."""
        if self.hook_path.exists() and not force:
            backup_path = self.hook_path.with_suffix(".backup")
            shutil.copy(self.hook_path, backup_path)
            print(f"  Backed up existing hook to {backup_path}")
        with open(self.hook_path, "w") as f:
            f.write(self.WRAPPER_TEMPLATE)
        os.chmod(self.hook_path, 0o755)
        print(f"  Hook wrapper installed: {self.hook_path}")

    def _try_immutable(self):
        """Attempt to set Unix immutable attribute (requires root)."""
        try:
            subprocess.run(["chattr", "+i", str(self.hook_path)], capture_output=True, shell=False)
            if os.path.exists("/usr/bin/lsattr"):
                subprocess.run(["lsattr", str(self.hook_path)], capture_output=True, shell=False)
            print("  Immutable attribute set (if supported)")
        except Exception:
            pass

    def verify(self) -> bool:
        """Verify hook has not been tampered with."""
        if not self.hook_path.exists():
            print("Hook file missing!")
            return False
        if not self.core_path.exists():
            print("Core module missing!")
            return False
        with open(self.hook_path, "r") as f:
            content = f.read()
        if "Agent-Proof Hook" not in content:
            print("Hook content has been modified!")
            return False
        with open(self.core_path, "r") as f:
            core = f.read()
        if "def enforce()" not in core:
            print("Core module has been modified!")
            return False
        print("Hook verification passed")
        return True

    def uninstall(self):
        """Uninstall hook and restore backup."""
        try:
            subprocess.run(["chattr", "-i", str(self.hook_path)], capture_output=True, shell=False)
        except Exception:
            pass
        if self.core_path.exists():
            self.core_path.unlink()
        if self.hook_path.exists():
            backup = self.hook_path.with_suffix(".backup")
            if backup.exists():
                shutil.copy(backup, self.hook_path)
                backup.unlink()
            else:
                self.hook_path.unlink()
        print("Agent-Proof Hook uninstalled")


def main():
    """CLI entry point."""
    hook = AgentProofHook()
    if len(sys.argv) > 1:
        cmd = sys.argv[1]
        if cmd == "install":
            hook.install(force=True)
        elif cmd == "verify":
            if not hook.verify():
                sys.exit(1)
        elif cmd == "uninstall":
            hook.uninstall()
        else:
            print(f"Unknown command: {cmd}")
            print("Available: install, verify, uninstall")
    else:
        hook.install()


if __name__ == "__main__":
    main()
