"""Orchestration — pipeline integration layer.

Bridges CLI commands to quality gate checks with feedback loops.
Provides retry-aware wrappers around constitution, enforcement, and gate runners.

Exports:
    run_constitution_check_with_feedback: constitution check with retry/fix loop.
"""

from __future__ import annotations

from pathlib import Path


def run_constitution_check_with_feedback(
    check_type: str,
    docs_path: str,
    current_phase: int = 1,
    *,
    max_retries: int = 3,
    auto_fix: bool = False,
) -> "ConstitutionResult":
    """Run constitution check with automatic retry and feedback.

    Called by harness_cli.py and the run-pipeline flow.

    On failure, suggests fix commands and retries up to max_retries times.
    If auto_fix is True, attempts to auto-generate missing artifacts.

    Args:
        check_type: Artifact type ("srs", "sad", "implementation", etc.).
        docs_path: Path to docs/ directory.
        current_phase: Current pipeline phase.
        max_retries: Maximum fix-retry cycles.
        auto_fix: Whether to attempt auto-fix on violations.

    Returns:
        ConstitutionResult with .score, .passed, .violations.
    """
    from core.quality_gate.constitution.runner import run_constitution_check

    result = run_constitution_check(
        check_type=check_type,
        docs_path=docs_path,
        current_phase=current_phase,
        check_mode="preflight",
        strict=False,
    )

    retry = 0
    while not result.passed and retry < max_retries:
        retry += 1
        print(f"\n[orchestration] Constitution check retry {retry}/{max_retries} — "
              f"score={result.score:.0f}%")

        if auto_fix:
            _attempt_auto_fix(result, docs_path, current_phase)

        # Re-run after fix attempt
        result = run_constitution_check(
            check_type=check_type,
            docs_path=docs_path,
            current_phase=current_phase,
            check_mode="postflight",
            strict=False,
        )

    return result


def _attempt_auto_fix(
    result,
    docs_path: str,
    current_phase: int,
) -> None:
    """Attempt to auto-fix common constitution violations.

    Handles:
    - Missing artifact stubs (generates minimal template)
    - Low compliance (adds boilerplate section headers)
    """
    path = Path(docs_path)
    from core.quality_gate.constitution.runner import _PHASE_DIR_MAP

    phase_dir_name = _PHASE_DIR_MAP.get(current_phase, "")
    if not phase_dir_name:
        return

    artifact_dir = path.parent / phase_dir_name if path.name == "docs" else path
    artifact_dir.mkdir(parents=True, exist_ok=True)

    for violation in result.violations:
        file_path = path.parent / violation.get("file", "")
        if not file_path.parent.exists():
            file_path.parent.mkdir(parents=True, exist_ok=True)

        if not file_path.exists():
            _generate_stub(file_path, current_phase)


def _generate_stub(file_path: Path, phase: int) -> None:
    """Generate a minimal artifact stub with constitution-compliance boilerplate."""
    stub_content = f"""# Phase {phase} Artifact — Auto-Generated Stub

> ⚠️ This stub was auto-generated by orchestration.
> Replace with actual artifact content before Gate evaluation.

## Overview

## Functional Requirements

### FR-01:

## Non-Functional Requirements

## Quality Gate Compliance

- Test Coverage: TBD
- Security: TBD
- Maintainability: TBD

## Traceability

| FR | Source | Implementation | Test |
|----|--------|---------------|------|
"""
    file_path.write_text(stub_content, encoding="utf-8")
    print(f"   [auto-fix] Generated stub: {file_path}")


# Re-export for external consumers
from core.quality_gate.constitution.runner import ConstitutionResult  # noqa: E402, F401

__all__ = ["run_constitution_check_with_feedback", "ConstitutionResult"]
