"""Phase 8 (Configuration Management) workflow assembly — Round 15 station2
extraction from the former monolithic phase_specs.py. See
scripts/workflowgen/spec_shared.py for the cross-phase _render_meta.
"""
from __future__ import annotations

from . import js_blocks as B
from . import spec_shared as S
from .spec_shared import _render_meta

_HEADER_8 = """\
// Phase 8 — Configuration Management (faithful to .methodology/phase8_plan.md v2.12.0)
//
// GENERATED FILE — do not hand-edit. Source of truth:
// scripts/workflowgen/phase_specs.py::generate_phase8() (+ js_blocks.py for
// the blocks shared across phase workflow files). Regenerate with:
//   python3 scripts/workflowgen/generate_workflows.py --write --phase 8
//
// Structure: FR-loop型 → push-milestone p8 → advance-phase --completed 8 → Sync → Phase 9 (Maintenance).
// Per-FR GATE1-DELTA re-eval, then REVIEW+APPEND the config baseline (the
// framework deterministically generated CONFIG_RECORDS.md + RELEASE_CHECKLIST.md
// via `scripts/phase8_doc_gen.py` during P7→P8 advance-phase (cli/phase_cmds.py
// advance-phase hook, harness commits 4738542 + 3f1fd73), create .methodology-archive/
// (cp -r .methodology/ — NOT .sessi-work/, per harness commit 3f1fd73), p8
// milestone push, advance-phase into Phase 9.
//
// Playbook lessons: NO import/fs/process, Bash CLI, SCOPE RULES,
// PY = .venv/bin/python, scriptPath launch.
// v4 (2026-07-02): gate verdicts use FLAT schema (playbook §5.2 rev) — regex
// over LLM prose was the root cause of the #126/#134/#135/#136/ENV_CHECK_RC
// bug class. Heavy orchestrators keep prose narrative; verdicts come from
// schema proxy agents reading harness artifacts (manifest qc, git log, rc).
"""

_META_PHASES_8 = [
    "Entry & Preflight", "Env Check", "Load FRs",
    "Per-FR Delta", "Config Docs", "Artifacts Commit", "Archive",
    "Preview Next-Phase", "Milestone", "Advance", "Sync",
]


def _render_config_docs() -> str:
    return (
        B.render_phase_header("Config Docs")
        + "// Per phase8_plan.md + harness commit 4738542: CONFIG_RECORDS.md and\n"
        + "// RELEASE_CHECKLIST.md are DETERMINISTICALLY generated by scripts/phase8_doc_gen.py\n"
        + "// during P7→P8 advance-phase (cli/phase_cmds.py:554, P7→P8 advance-phase hook).\n"
        + "// P8 work is therefore REVIEW + APPEND human-only context, NOT regenerate from\n"
        + "// scratch. Do NOT overwrite the deterministic baseline (it breaks byte-equality\n"
        + "// for downstream consumers); use Edit/append to add the human-only sections.\n"
        + "log('Review deterministic baseline (phase8_doc_gen.py output) + append human-only context')\n"
        + "const docsReport = await agent(\n"
        + "  'YOU ARE THE P8 CONFIG REVIEWER. The framework has ALREADY deterministically generated\\n'\n"
        + "  + 'the config baseline during P7→P8 advance-phase. Your job: REVIEW + APPEND.\\n'\n"
        + "  + 'REPO: ' + REPO + '\\nPYTHON: ' + PY + '\\n\\n'\n"
        + "  + 'Steps (Bash for read-only checks; Edit for human-only append):\\n'\n"
        + "  + '0. VERIFY BASELINE EXISTS: `test -f ' + REPO + '/08-config/CONFIG_RECORDS.md && test -f ' + REPO + '/08-config/RELEASE_CHECKLIST.md && echo BASELINE_OK || echo BASELINE_MISSING`. If MISSING, regenerate via `' + PY + ' ' + REPO + '/harness/scripts/phase8_doc_gen.py --project ' + REPO + '` (fallback per harness advance-phase behavior; should not normally fire).\\n'\n"
        + "  + '1. CONFIG_RECORDS APPEND: Edit ' + REPO + '/08-config/CONFIG_RECORDS.md and APPEND a `## Human Context (P8 append)` section with: ownership per config item, secret rotation cadence, access audit log reference. KEEP all existing framework-generated sections (env var inventory, source-of-truth module refs, feature flags) intact. Do NOT overwrite the framework version.\\n'\n"
        + "  + '1b. CONFIG_RECORDS FILL: the baseline is copied from a template and still carries the placeholders of that template — `{config}` for both environments, `{VAR}` / `{description}` in the environment-variable table, `{method}` / `{name}` in the deployment log, `{change}` / `{reason}` in the change log, and `{condition}` / `{rollback commands}` for the entire Rollback SOP. Replace EACH of them in place with the real value for this release; where a section genuinely does not apply, say so in words and delete the placeholder. Round 55 站2: `cross_artifact.check_unfilled_placeholders` now reports every surviving one as CRITICAL, and it is a CRITICAL that fails Phase Truth. Measured before it existed: all seven projects built by this framework shipped the same nine placeholders, rollback SOP included.\\n'\n"
        + "  + '2. RELEASE_CHECKLIST APPEND: Edit ' + REPO + '/08-config/RELEASE_CHECKLIST.md and APPEND a `## Human Context (P8 append)` section with: deployment runbook URL, rollback owner + on-call, post-release monitoring dashboard, customer comms template. KEEP the framework-rendered table (phases, Gate 4 verdict, open findings, commit) and the PENDING-HUMAN boxes intact — never tick a PENDING-HUMAN box: only the named person can.\\n'\n"
        + "  + '3. SANITY: `grep -c \"^## \" ' + REPO + '/08-config/CONFIG_RECORDS.md && grep -c \"^## \" ' + REPO + '/08-config/RELEASE_CHECKLIST.md` — confirm both files still have the framework sections (count >= baseline).\\n\\n'\n"
        + "  + 'Verdict: report via the StructuredOutput tool — pass=true ONLY if the baseline was verified AND human context appended; reason = one-line summary.\\n\\n'\n"
        + "  + 'SCOPE RULES:\\n- DO NOT regenerate CONFIG_RECORDS.md / RELEASE_CHECKLIST.md from scratch.\\n- DO NOT use Write tool to overwrite either file — Edit/append only.\\n- DO NOT run push-milestone / create archive (next phases do that).\\n- DO NOT modify harness/.\\n- DO NOT re-implement FRs.\\n- ONLY verify baseline + append human context.',\n"
        + "  { label: 'config-docs', phase: 'Config Docs', agentType: 'general-purpose', schema: VERDICT_SCHEMA },\n"
        + ")\n"
        + "if (!(docsReport && docsReport.pass === true)) {\n"
        + "  return halt('config-docs', { error: 'Phase 8 config docs did not PASS', reason: docsReport ? String(docsReport.reason ?? '').slice(-500) : 'agent returned null' })\n"
        + "}\n"
    )


def _render_archive() -> str:
    return (
        B.render_phase_header("Archive")
        + "// P8-ARCHIVE — required by CI p8-archive-check. (Round 115 站4: the step that\n"
        + "// deleted Phase 9 references from HANDOVER.md is gone — Phase 9 is a real phase.)\n"
        + "log('Create .methodology-archive/')\n"
        + "const archiveReport = await agent(\n"
        + "  'YOU ARE THE P8 ARCHIVE ORCHESTRATOR. Prepare the archive (REQUIRED before p8 push).\\n'\n"
        + "  + 'REPO: ' + REPO + '\\n\\n'\n"
        + "  + 'Steps (Bash):\\n'\n"
        + "  + '1. P8-ARCHIVE: `mkdir -p ' + REPO + '/.methodology-archive && cp -r ' + REPO + '/.methodology/ ' + REPO + '/.methodology-archive/`. (push-milestone _validate_p8_completion + CI p8-archive-check both verify this dir. Source MUST be `.methodology/` — NOT `.sessi-work/` per harness commit 3f1fd73 which fixed the wrong-source silent bug.)\\n\\n'\n"
        + "  + 'Verdict: report via the StructuredOutput tool — pass=true ONLY if the archive dir was created; reason = one-line summary.\\n\\n'\n"
        + "  + 'SCOPE RULES:\\n- DO NOT run push-milestone yet.\\n- DO NOT modify harness/.\\n- ONLY create .methodology-archive/.',\n"
        + "  { label: 'archive', phase: 'Archive', agentType: 'general-purpose', schema: VERDICT_SCHEMA },\n"
        + ")\n"
        + "if (!(archiveReport && archiveReport.pass === true)) {\n"
        + "  return halt('archive-prep', { error: 'Phase 8 archive prep did not PASS', reason: archiveReport ? String(archiveReport.reason ?? '').slice(-500) : 'agent returned null' })\n"
        + "}\n"
    )


def generate_phase8() -> str:
    parts = [
        _HEADER_8,
        "",
        _render_meta(
            name="phase8-config",
            description=(
                "Phase 8 Config — per-FR GATE1-DELTA + "
                "CONFIG_RECORDS/RELEASE_CHECKLIST + archive + p8 push "
                "(phase8_plan.md v2.12.0)"
            ),
            phases=_META_PHASES_8,
        ),
        "",
        B.RESOLVE_REPO_BLOCK + B.REPO_LOG_LINE + B.BUDGET_GUARD_BLOCK,
        "",
        B.WRITE_SCOPE_BLOCK,
        "",
        B.render_schemas(["VERDICT_SCHEMA", "RC_SCHEMA", "FR_STEP_SCHEMA", "ENV_CHECK_SCHEMA", "CTX_SCHEMA", "DELTA_FAST_SCHEMA", "PHASE_SCHEMA"]),
        B.render_change_review(),  # Round 114 站6
        B.render_entry_preflight(
            phase=8, gate_num=4, gate_owner_phase=6, prev_phase=7,
            extra_note=(
                "- DO NOT generate config docs / run TDD steps / create archive.\\n"
                "- DO NOT run push-milestone.\\n"
            ),
        ),
        B.render_env_check(phase=8),
        B.render_load_frs(phase=8),
        B.render_per_fr_delta(
            phase=8,
            forbidden_note="- DO NOT run push-milestone / generate config docs / create archive.\\n",
            verifier_role="CONFIG-AWARE VERIFIER",
        ),
        _render_config_docs(),
        B.render_artifacts_commit(
            paths=["08-config/CONFIG_RECORDS.md", "08-config/RELEASE_CHECKLIST.md", ".methodology"],
            commit_msg="chore(p8): config-records + release-checklist artifacts",
            phase=8,
        ),
        _render_archive(),
        B.render_preview_next_phase(8),
        # Round 115 站4: P7's shape. The hand-rolled Final Push stopped at "p8
        # already pushed" before its advance step and read the milestone alone
        # as PASS; the advance loop's guard is the phase cursor (Round 95).
        B.render_milestone(
            phase=8, milestone_type="p8", guard_grep="P8",
            label="milestone-p8",
            extra_note=" (config records + archive complete)",
        ),
        B.render_advance_loop(
            phase=8, next_phase=9,
            scope_extra="- DO NOT re-do P8 config docs or the archive.\\n",
            log_msg="advance-phase --completed 8 → Phase 9 (Maintenance, CR-driven)",
        ),
        B.render_sync_verified(extra_lines=[
            "3. `git -C ' + REPO + ' tag -l \\\"harness-v*\\\" | head -3` — confirm any Phase 6 gate4 tag is pushed; if there is a P6 tag but `git push origin --tags` hasn\\'t run yet, push tags.",
        ]),
        (
            "\nreturn {\n"
            + S.render_phase_complete_marker()
            +
            "  phase: 8,\n"
            "  fr_count: frIds.length,\n"
            "  gate1_pass: gate1Pass,\n"
            "  advance_status: 'PASS',\n"
            "  artifacts: ['08-config/CONFIG_RECORDS.md', '08-config/RELEASE_CHECKLIST.md', '.methodology-archive/', 'HANDOVER.md'],\n"
            "  notes: 'Phase 8 complete per phase8_plan.md v2.12.0: a release candidate — the PENDING-HUMAN items in 08-config/RELEASE_CHECKLIST.md are not verified by the framework. Phase 9 (Maintenance, CR-driven steady state).',\n"
            "}\n"
        ),
    ]
    return "\n".join(p for p in parts if p is not None)
